<?php

namespace App\Models\StrukturUmur\Disabilitas;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PendidikanUmurTunggal extends Model
{
    use HasFactory,SoftDeletes;
    public $table = 'pendidikan_umur_tunggal_disabilitas';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'uuid',
        'kode_wilayah',
        'umur',
        'fisik_tidak_blm_sekolah_l',
        'fisik_tidak_blm_sekolah_p',
        'fisik_tidak_blm_sekolah',
        'fisik_belum_tamat_sd_sederajat_l',
        'fisik_belum_tamat_sd_sederajat_p',
        'fisik_belum_tamat_sd_sederajat',
        'fisik_tamat_sd_sederajat_l',
        'fisik_tamat_sd_sederajat_p',
        'fisik_tamat_sd_sederajat',
        'fisik_sltp_sederajat_l',
        'fisik_sltp_sederajat_p',
        'fisik_sltp_sederajat',
        'fisik_slta_sederajat_l',
        'fisik_slta_sederajat_p',
        'fisik_slta_sederajat',
        'fisik_diploma_i_ii_l',
        'fisik_diploma_i_ii_p',
        'fisik_diploma_i_ii',
        'fisik_akademi_diploma_iii_s_muda_l',
        'fisik_akademi_diploma_iii_s_muda_p',
        'fisik_akademi_diploma_iii_s_muda',
        'fisik_diploma_iv_strata_i_l',
        'fisik_diploma_iv_strata_i_p',
        'fisik_diploma_iv_strata_i',
        'fisik_strata_ii_l',
        'fisik_strata_ii_p',
        'fisik_strata_ii',
        'fisik_strata_iii_l',
        'fisik_strata_iii_p',
        'fisik_strata_iii',
        'netra_buta_tidak_blm_sekolah_l',
        'netra_buta_tidak_blm_sekolah_p',
        'netra_buta_tidak_blm_sekolah',
        'netra_buta_belum_tamat_sd_sederajat_l',
        'netra_buta_belum_tamat_sd_sederajat_p',
        'netra_buta_belum_tamat_sd_sederajat',
        'netra_buta_tamat_sd_sederajat_l',
        'netra_buta_tamat_sd_sederajat_p',
        'netra_buta_tamat_sd_sederajat',
        'netra_buta_sltp_sederajat_l',
        'netra_buta_sltp_sederajat_p',
        'netra_buta_sltp_sederajat',
        'netra_buta_slta_sederajat_l',
        'netra_buta_slta_sederajat_p',
        'netra_buta_slta_sederajat',
        'netra_buta_diploma_i_ii_l',
        'netra_buta_diploma_i_ii_p',
        'netra_buta_diploma_i_ii',
        'netra_buta_akademi_diploma_iii_s_muda_l',
        'netra_buta_akademi_diploma_iii_s_muda_p',
        'netra_buta_akademi_diploma_iii_s_muda',
        'netra_buta_diploma_iv_strata_i_l',
        'netra_buta_diploma_iv_strata_i_p',
        'netra_buta_diploma_iv_strata_i',
        'netra_buta_strata_ii_l',
        'netra_buta_strata_ii_p',
        'netra_buta_strata_ii',
        'netra_buta_strata_iii_l',
        'netra_buta_strata_iii_p',
        'netra_buta_strata_iii',
        'rungu_wicara_tidak_blm_sekolah_l',
        'rungu_wicara_tidak_blm_sekolah_p',
        'rungu_wicara_tidak_blm_sekolah',
        'rungu_wicara_belum_tamat_sd_sederajat_l',
        'rungu_wicara_belum_tamat_sd_sederajat_p',
        'rungu_wicara_belum_tamat_sd_sederajat',
        'rungu_wicara_tamat_sd_sederajat_l',
        'rungu_wicara_tamat_sd_sederajat_p',
        'rungu_wicara_tamat_sd_sederajat',
        'rungu_wicara_sltp_sederajat_l',
        'rungu_wicara_sltp_sederajat_p',
        'rungu_wicara_sltp_sederajat',
        'rungu_wicara_slta_sederajat_l',
        'rungu_wicara_slta_sederajat_p',
        'rungu_wicara_slta_sederajat',
        'rungu_wicara_diploma_i_ii_l',
        'rungu_wicara_diploma_i_ii_p',
        'rungu_wicara_diploma_i_ii',
        'rungu_wicara_akademi_diploma_iii_s_muda_l',
        'rungu_wicara_akademi_diploma_iii_s_muda_p',
        'rungu_wicara_akademi_diploma_iii_s_muda',
        'rungu_wicara_diploma_iv_strata_i_l',
        'rungu_wicara_diploma_iv_strata_i_p',
        'rungu_wicara_diploma_iv_strata_i',
        'rungu_wicara_strata_ii_l',
        'rungu_wicara_strata_ii_p',
        'rungu_wicara_strata_ii',
        'rungu_wicara_strata_iii_l',
        'rungu_wicara_strata_iii_p',
        'rungu_wicara_strata_iii',
        'lainnya_tidak_blm_sekolah_l',
        'lainnya_tidak_blm_sekolah_p',
        'lainnya_tidak_blm_sekolah',
        'lainnya_belum_tamat_sd_sederajat_l',
        'lainnya_belum_tamat_sd_sederajat_p',
        'lainnya_belum_tamat_sd_sederajat',
        'lainnya_tamat_sd_sederajat_l',
        'lainnya_tamat_sd_sederajat_p',
        'lainnya_tamat_sd_sederajat',
        'lainnya_sltp_sederajat_l',
        'lainnya_sltp_sederajat_p',
        'lainnya_sltp_sederajat',
        'lainnya_slta_sederajat_l',
        'lainnya_slta_sederajat_p',
        'lainnya_slta_sederajat',
        'lainnya_diploma_i_ii_l',
        'lainnya_diploma_i_ii_p',
        'lainnya_diploma_i_ii',
        'lainnya_akademi_diploma_iii_s_muda_l',
        'lainnya_akademi_diploma_iii_s_muda_p',
        'lainnya_akademi_diploma_iii_s_muda',
        'lainnya_diploma_iv_strata_i_l',
        'lainnya_diploma_iv_strata_i_p',
        'lainnya_diploma_iv_strata_i',
        'lainnya_strata_ii_l',
        'lainnya_strata_ii_p',
        'lainnya_strata_ii',
        'lainnya_strata_iii_l',
        'lainnya_strata_iii_p',
        'lainnya_strata_iii',
        'semester',
        'tahun',
    ];
    
}
