<?php

return [
    'listFileImport' => [
        '1' => 'App\Imports\DisabilitasJenisKelaminImport',
        '2' => 'App\Imports\DisabilitasPekerjaanImport',
        '3' => 'App\Imports\DisabilitasPendidikanImport',
        '4' => 'App\Imports\KepalaKeluargaJenisKelaminImport',
        '5' => 'App\Imports\KepalaKeluargaAgamaImport',
        '6' => 'App\Imports\KepalaKeluargaPekerjaanImport',
        '7' => 'App\Imports\KepalaKeluargaPendidikanImport',
        '8' => 'App\Imports\KepalaKeluargaStatusKawinImport',
        '9' => 'App\Imports\PendidikanGolonganDarahImport',
        '10' => 'App\Imports\PendidikanJenisKelaminImport',
        '11' => 'App\Imports\PendudukJenisKelaminImport',
        '12' => 'App\Imports\PendudukAgamaImport',
        '13' => 'App\Imports\PendudukGolonganDarahImport',
        '14' => 'App\Imports\PendudukHubungaKeluargaImport',
        '15' => 'App\Imports\PendudukPekerjaanImport',
        '16' => 'App\Imports\KepemilikanAktaCeraiImport',
        '17' => 'App\Imports\KepemilikanAktaKawinImport',
        '18' => 'App\Imports\KepemilikanAktaKelahiranImport',
        '19' => 'App\Imports\KepemilikanKartuKeluargaImport',
        '20' => 'App\Imports\KepemilikanKIAImport',
        '21' => 'App\Imports\KepemilikanAktaCeraiAgamaImport',
        '22' => 'App\Imports\KepemilikanAktaAgamaKawinImport',
        '23' => 'App\Imports\StrukturUmurAgamaKelompokUmurImport',
        '24' => 'App\Imports\StrukturUmurDisabilitasKelompokUmurImport',
        '25' => 'App\Imports\StrukturUmurDisabilitasPendidikanUmurTunggalImport',
        '26' => 'App\Imports\StrukturUmurDisabilitasUmurTunggalImport',
        '27' => 'App\Imports\StrukturUmurDisabilitasUsiaSekolahKelompokUmurImport',
        '28' => 'App\Imports\StrukturUmurGolonganDarahKelompokUmurImport',
        '29' => 'App\Imports\StrukturUmurGolonganDarahUmurTunggalImport',
        '30' => 'App\Imports\StrukturUmurKepalaKeluargaKelompokUmurImport',
        '31' => 'App\Imports\StrukturUmurKepalaKeluargaStatusKawinImport',
        '32' => 'App\Imports\StrukturUmurKepalaKeluargaUmurTunggalImport',
        '33' => 'App\Imports\StrukturUmurPendudukKelompokUmurImport',
        '34' => 'App\Imports\StrukturUmurPendudukStatusKawinKelompokUmurImport',
        '35' => 'App\Imports\StrukturUmurPendudukStatusKawinUmurTunggalImport',
        '36' => 'App\Imports\StrukturUmurPendudukUmurTunggalImport',
        '37' => 'App\Imports\StrukturUmurPendudukUsiaMudaProduktifImport',
        '38' => 'App\Imports\StrukturUmurPendudukUsiaSekolahImport',
    ],
    'listFileModel' => [
        '1' => 'App\Models\AgregatDKB\Disabilitas\JenisKelamin',
        '2' => 'App\Models\AgregatDKB\Disabilitas\Pekerjaan',
        '3' => 'App\Models\AgregatDKB\Disabilitas\Pendidikan',
        '4' => 'App\Models\AgregatDKB\KepalaKeluarga\JenisKelamin',
        '5' => 'App\Models\AgregatDKB\KepalaKeluarga\Agama',
        '6' => 'App\Models\AgregatDKB\KepalaKeluarga\Pekerjaan',
        '7' => 'App\Models\AgregatDKB\KepalaKeluarga\Pendidikan',
        '8' => 'App\Models\AgregatDKB\KepalaKeluarga\StatusKawin',
        '9' => 'App\Models\AgregatDKB\Pendidikan\GolonganDarah',
        '10' => 'App\Models\AgregatDKB\Pendidikan\JenisKelamin',
        '11' => 'App\Models\AgregatDKB\Penduduk\JenisKelamin',
        '12' => 'App\Models\AgregatDKB\Penduduk\Agama',
        '13' => 'App\Models\AgregatDKB\Penduduk\GolonganDarah',
        '14' => 'App\Models\AgregatDKB\Penduduk\HubungaKeluarga',
        '15' => 'App\Models\AgregatDKB\Penduduk\Pekerjaan',
        '16' => 'App\Models\Kepemilikan\AktaCerai',
        '17' => 'App\Models\Kepemilikan\AktaKawin',
        '18' => 'App\Models\Kepemilikan\AktaKelahiran',
        '19' => 'App\Models\Kepemilikan\KartuKeluarga',
        '20' => 'App\Models\Kepemilikan\KIA',
        '21' => 'App\Models\Kepemilikan\AktaCeraiAgama',
        '22' => 'App\Models\Kepemilikan\AktaAgamaKawin',
        '23' => 'App\Models\StrukturUmur\Agama\KelompokUmur',
        '24' => 'App\Models\StrukturUmur\Disabilitas\KelompokUmur',
        '25' => 'App\Models\StrukturUmur\Disabilitas\PendidikanUmurTunggal',
        '26' => 'App\Models\StrukturUmur\Disabilitas\UmurTunggal',
        '27' => 'App\Models\StrukturUmur\Disabilitas\UsiaSekolahKelompokUmur',
        '28' => 'App\Models\StrukturUmur\GolonganDarah\KelompokUmur',
        '29' => 'App\Models\StrukturUmur\GolonganDarah\UmurTunggal',
        '30' => 'App\Models\StrukturUmur\KepalaKeluarga\KelompokUmur',
        '31' => 'App\Models\StrukturUmur\KepalaKeluarga\StatusKawin',
        '32' => 'App\Models\StrukturUmur\KepalaKeluarga\UmurTunggal',
        '33' => 'App\Models\StrukturUmur\Penduduk\KelompokUmur',
        '34' => 'App\Models\StrukturUmur\Penduduk\StatusKawinKelompokUmur',
        '35' => 'App\Models\StrukturUmur\Penduduk\StatusKawinUmurTunggal',
        '36' => 'App\Models\StrukturUmur\Penduduk\UmurTunggal',
        '37' => 'App\Models\StrukturUmur\Penduduk\UsiaMudaProduktif',
        '38' => 'App\Models\StrukturUmur\Penduduk\UsiaSekolah',
    ],
    'listCalculateDataFunction' => [
        'CV8V59hUCF' => 'dataPendudukJenisKelamin',
    ],
    'categoryEducationDisabilites' => [
        'fisik_tidak_blm_sekolah_l',
        'fisik_tidak_blm_sekolah_p',
        'fisik_tidak_blm_sekolah',
        'fisik_belum_tamat_sd_sederajat_l',
        'fisik_belum_tamat_sd_sederajat_p',
        'fisik_belum_tamat_sd_sederajat',
        'fisik_tamat_sd_sederajat_l',
        'fisik_tamat_sd_sederajat_p',
        'fisik_tamat_sd_sederajat',
        'fisik_sltp_sederajat_l',
        'fisik_sltp_sederajat_p',
        'fisik_sltp_sederajat',
        'fisik_slta_sederajat_l',
        'fisik_slta_sederajat_p',
        'fisik_slta_sederajat',
        'fisik_diploma_i_ii_l',
        'fisik_diploma_i_ii_p',
        'fisik_diploma_i_ii',
        'fisik_akademi_diploma_iii_s_muda_l',
        'fisik_akademi_diploma_iii_s_muda_p',
        'fisik_akademi_diploma_iii_s_muda',
        'fisik_diploma_iv_strata_i_l',
        'fisik_diploma_iv_strata_i_p',
        'fisik_diploma_iv_strata_i',
        'fisik_strata_ii_l',
        'fisik_strata_ii_p',
        'fisik_strata_ii',
        'fisik_strata_iii_l',
        'fisik_strata_iii_p',
        'fisik_strata_iii',
        'netra_buta_tidak_blm_sekolah_l',
        'netra_buta_tidak_blm_sekolah_p',
        'netra_buta_tidak_blm_sekolah',
        'netra_buta_belum_tamat_sd_sederajat_l',
        'netra_buta_belum_tamat_sd_sederajat_p',
        'netra_buta_belum_tamat_sd_sederajat',
        'netra_buta_tamat_sd_sederajat_l',
        'netra_buta_tamat_sd_sederajat_p',
        'netra_buta_tamat_sd_sederajat',
        'netra_buta_sltp_sederajat_l',
        'netra_buta_sltp_sederajat_p',
        'netra_buta_sltp_sederajat',
        'netra_buta_slta_sederajat_l',
        'netra_buta_slta_sederajat_p',
        'netra_buta_slta_sederajat',
        'netra_buta_diploma_i_ii_l',
        'netra_buta_diploma_i_ii_p',
        'netra_buta_diploma_i_ii',
        'netra_buta_akademi_diploma_iii_s_muda_l',
        'netra_buta_akademi_diploma_iii_s_muda_p',
        'netra_buta_akademi_diploma_iii_s_muda',
        'netra_buta_diploma_iv_strata_i_l',
        'netra_buta_diploma_iv_strata_i_p',
        'netra_buta_diploma_iv_strata_i',
        'netra_buta_strata_ii_l',
        'netra_buta_strata_ii_p',
        'netra_buta_strata_ii',
        'netra_buta_strata_iii_l',
        'netra_buta_strata_iii_p',
        'netra_buta_strata_iii',
        'rungu_wicara_tidak_blm_sekolah_l',
        'rungu_wicara_tidak_blm_sekolah_p',
        'rungu_wicara_tidak_blm_sekolah',
        'rungu_wicara_belum_tamat_sd_sederajat_l',
        'rungu_wicara_belum_tamat_sd_sederajat_p',
        'rungu_wicara_belum_tamat_sd_sederajat',
        'rungu_wicara_tamat_sd_sederajat_l',
        'rungu_wicara_tamat_sd_sederajat_p',
        'rungu_wicara_tamat_sd_sederajat',
        'rungu_wicara_sltp_sederajat_l',
        'rungu_wicara_sltp_sederajat_p',
        'rungu_wicara_sltp_sederajat',
        'rungu_wicara_slta_sederajat_l',
        'rungu_wicara_slta_sederajat_p',
        'rungu_wicara_slta_sederajat',
        'rungu_wicara_diploma_i_ii_l',
        'rungu_wicara_diploma_i_ii_p',
        'rungu_wicara_diploma_i_ii',
        'rungu_wicara_akademi_diploma_iii_s_muda_l',
        'rungu_wicara_akademi_diploma_iii_s_muda_p',
        'rungu_wicara_akademi_diploma_iii_s_muda',
        'rungu_wicara_diploma_iv_strata_i_l',
        'rungu_wicara_diploma_iv_strata_i_p',
        'rungu_wicara_diploma_iv_strata_i',
        'rungu_wicara_strata_ii_l',
        'rungu_wicara_strata_ii_p',
        'rungu_wicara_strata_ii',
        'rungu_wicara_strata_iii_l',
        'rungu_wicara_strata_iii_p',
        'rungu_wicara_strata_iii',
        'lainnya_tidak_blm_sekolah_l',
        'lainnya_tidak_blm_sekolah_p',
        'lainnya_tidak_blm_sekolah',
        'lainnya_belum_tamat_sd_sederajat_l',
        'lainnya_belum_tamat_sd_sederajat_p',
        'lainnya_belum_tamat_sd_sederajat',
        'lainnya_tamat_sd_sederajat_l',
        'lainnya_tamat_sd_sederajat_p',
        'lainnya_tamat_sd_sederajat',
        'lainnya_sltp_sederajat_l',
        'lainnya_sltp_sederajat_p',
        'lainnya_sltp_sederajat',
        'lainnya_slta_sederajat_l',
        'lainnya_slta_sederajat_p',
        'lainnya_slta_sederajat',
        'lainnya_diploma_i_ii_l',
        'lainnya_diploma_i_ii_p',
        'lainnya_diploma_i_ii',
        'lainnya_akademi_diploma_iii_s_muda_l',
        'lainnya_akademi_diploma_iii_s_muda_p',
        'lainnya_akademi_diploma_iii_s_muda',
        'lainnya_diploma_iv_strata_i_l',
        'lainnya_diploma_iv_strata_i_p',
        'lainnya_diploma_iv_strata_i',
        'lainnya_strata_ii_l',
        'lainnya_strata_ii_p',
        'lainnya_strata_ii',
        'lainnya_strata_iii_l',
        'lainnya_strata_iii_p',
        'lainnya_strata_iii',
    ],
    'categoryDisabilities' => [
        'disabiltas_fisik_lk',
        'disabiltas_fisik_pr',
        'disabiltas_fisik_jml',
        'disabiltas_netra_buta_lk',
        'disabiltas_netra_buta_pr',
        'disabiltas_netra_buta_jml',
        'disabiltas_rungu_wicara_lk',
        'disabiltas_rungu_wicara_pr',
        'disabiltas_rungu_wicara_jml',
        'disabiltas_mental_jiwa_lk',
        'disabiltas_mental_jiwa_pr',
        'disabiltas_mental_jiwa_jml',
        'disabiltas_fisik_mental_lk',
        'disabiltas_fisik_mental_pr',
        'disabiltas_fisik_mental_jml',
        'disabiltas_lainya_lk',
        'disabiltas_lainya_pr',
        'disabiltas_lainya_jml',
    ],
    'categoryAgeSchollDisabilities' => [
        'fisik_u4_6th_lk',
        'fisik_u4_6th_pr',
        'fisik_u7_12th_lk',
        'fisik_u7_12th_pr',
        'fisik_u13_15th_lk',
        'fisik_u13_15th_pr',
        'fisik_u16_18th_lk',
        'fisik_u16_18th_pr',
        'netra_buta_u4_6th_lk',
        'netra_buta_u4_6th_pr',
        'netra_buta_u7_12th_lk',
        'netra_buta_u7_12th_pr',
        'netra_buta_u13_15th_lk',
        'netra_buta_u13_15th_pr',
        'netra_buta_u16_18th_lk',
        'netra_buta_u16_18th_pr',
        'rungu_wicara_u4_6th_lk',
        'rungu_wicara_u4_6th_pr',
        'rungu_wicara_u7_12th_lk',
        'rungu_wicara_u7_12th_pr',
        'rungu_wicara_u13_15th_lk',
        'rungu_wicara_u13_15th_pr',
        'rungu_wicara_u16_18th_lk',
        'rungu_wicara_u16_18th_pr',
        'mental_jiwa_u4_6th_lk',
        'mental_jiwa_u4_6th_pr',
        'mental_jiwa_u7_12th_lk',
        'mental_jiwa_u7_12th_pr',
        'mental_jiwa_u13_15th_lk',
        'mental_jiwa_u13_15th_pr',
        'mental_jiwa_u16_18th_lk',
        'mental_jiwa_u16_18th_pr',
        'fisik_mental_u4_6th_lk',
        'fisik_mental_u4_6th_pr',
        'fisik_mental_u7_12th_lk',
        'fisik_mental_u7_12th_pr',
        'fisik_mental_u13_15th_lk',
        'fisik_mental_u13_15th_pr',
        'fisik_mental_u16_18th_lk',
        'fisik_mental_u16_18th_pr',
        'lainnya_u4_6th_lk',
        'lainnya_u4_6th_pr',
        'lainnya_u7_12th_lk',
        'lainnya_u7_12th_pr',
        'lainnya_u13_15th_lk',
        'lainnya_u13_15th_pr',
        'lainnya_u16_18th_lk',
        'lainnya_u16_18th_pr',
    ],
    'categoryBlood' => [
        'a_lk',
        'a_pr',
        'a_jml',
        'a_m_lk',
        'a_m_pr',
        'a_m_jml',
        'a_p_lk',
        'a_p_pr',
        'a_p_jml',
        'b_lk',
        'b_pr',
        'b_jml',
        'b_m_lk',
        'b_m_pr',
        'b_m_jml',
        'b_p_lk',
        'b_p_pr',
        'b_p_jml',
        'ab_lk',
        'ab_pr',
        'ab_jml',
        'ab_m_lk',
        'ab_m_pr',
        'ab_m_jml',
        'ab_p_lk',
        'ab_p_pr',
        'ab_p_jml',
        'o_lk',
        'o_pr',
        'o_jml',
        'o_m_lk',
        'o_m_pr',
        'o_m_jml',
        'o_p_lk',
        'o_p_pr',
        'o_p_jml',
        'tidak_tahu_lk',
        'tidak_tahu_pr',
        'tidak_tahu_jml',
    ],
    'categoryAgeGroup' => [
        '00_04_tahun_lk',
        '00_04_tahun_pr',
        '00_04_tahun_jml',
        '05_09_tahun_lk',
        '05_09_tahun_pr',
        '05_09_tahun_jml',
        '10_14_tahun_lk',
        '10_14_tahun_pr',
        '10_14_tahun_jml',
        '15_19_tahun_lk',
        '15_19_tahun_pr',
        '15_19_tahun_jml',
        '20_24_tahun_lk',
        '20_24_tahun_pr',
        '20_24_tahun_jml',
        '25_29_tahun_lk',
        '25_29_tahun_pr',
        '25_29_tahun_jml',
        '30_34_tahun_lk',
        '30_34_tahun_pr',
        '30_34_tahun_jml',
        '35_39_tahun_lk',
        '35_39_tahun_pr',
        '35_39_tahun_jml',
        '40_44_tahun_lk',
        '40_44_tahun_pr',
        '40_44_tahun_jml',
        '45_49_tahun_lk',
        '45_49_tahun_pr',
        '45_49_tahun_jml',
        '50_54_tahun_lk',
        '50_54_tahun_pr',
        '50_54_tahun_jml',
        '55_59_tahun_lk',
        '55_59_tahun_pr',
        '55_59_tahun_jml',
        '60_64_tahun_lk',
        '60_64_tahun_pr',
        '60_64_tahun_jml',
        '65_69_tahun_lk',
        '65_69_tahun_pr',
        '65_69_tahun_jml',
        '70_74_tahun_lk',
        '70_74_tahun_pr',
        '70_74_tahun_jml',
        'lebih_75_tahun_lk',
        'lebih_75_tahun_pr',
        'lebih_75_tahun_jml',
    ],
    'categoryAgeGroupMarriageStatus' => [
        '00_04_belum_kawin_lk',
        '00_04_belum_kawin_pr',
        '00_04_kawin_lk',
        '00_04_kawin_pr',
        '00_04_cerai_hidup_lk',
        '00_04_cerai_hidup_pr',
        '00_04_cerai_mati_lk',
        '00_04_cerai_mati_pr',
        '05_09_belum_kawin_lk',
        '05_09_belum_kawin_pr',
        '05_09_kawin_lk',
        '05_09_kawin_pr',
        '05_09_cerai_hidup_lk',
        '05_09_cerai_hidup_pr',
        '05_09_cerai_mati_lk',
        '05_09_cerai_mati_pr',
        '10_14_belum_kawin_lk',
        '10_14_belum_kawin_pr',
        '10_14_kawin_lk',
        '10_14_kawin_pr',
        '10_14_cerai_hidup_lk',
        '10_14_cerai_hidup_pr',
        '10_14_cerai_mati_lk',
        '10_14_cerai_mati_pr',
        '15_19_belum_kawin_lk',
        '15_19_belum_kawin_pr',
        '15_19_kawin_lk',
        '15_19_kawin_pr',
        '15_19_cerai_hidup_lk',
        '15_19_cerai_hidup_pr',
        '15_19_cerai_mati_lk',
        '15_19_cerai_mati_pr',
        '20_24_belum_kawin_lk',
        '20_24_belum_kawin_pr',
        '20_24_kawin_lk',
        '20_24_kawin_pr',
        '20_24_cerai_hidup_lk',
        '20_24_cerai_hidup_pr',
        '20_24_cerai_mati_lk',
        '20_24_cerai_mati_pr',
        '25_29_belum_kawin_lk',
        '25_29_belum_kawin_pr',
        '25_29_kawin_lk',
        '25_29_kawin_pr',
        '25_29_cerai_hidup_lk',
        '25_29_cerai_hidup_pr',
        '25_29_cerai_mati_lk',
        '25_29_cerai_mati_pr',
        '30_34_belum_kawin_lk',
        '30_34_belum_kawin_pr',
        '30_34_kawin_lk',
        '30_34_kawin_pr',
        '30_34_cerai_hidup_lk',
        '30_34_cerai_hidup_pr',
        '30_34_cerai_mati_lk',
        '30_34_cerai_mati_pr',
        '35_39_belum_kawin_lk',
        '35_39_belum_kawin_pr',
        '35_39_kawin_lk',
        '35_39_kawin_pr',
        '35_39_cerai_hidup_lk',
        '35_39_cerai_hidup_pr',
        '35_39_cerai_mati_lk',
        '35_39_cerai_mati_pr',
        '40_44_belum_kawin_lk',
        '40_44_belum_kawin_pr',
        '40_44_kawin_lk',
        '40_44_kawin_pr',
        '40_44_cerai_hidup_lk',
        '40_44_cerai_hidup_pr',
        '40_44_cerai_mati_lk',
        '40_44_cerai_mati_pr',
        '45_49_belum_kawin_lk',
        '45_49_belum_kawin_pr',
        '45_49_kawin_lk',
        '45_49_kawin_pr',
        '45_49_cerai_hidup_lk',
        '45_49_cerai_hidup_pr',
        '45_49_cerai_mati_lk',
        '45_49_cerai_mati_pr',
        '50_54_belum_kawin_lk',
        '50_54_belum_kawin_pr',
        '50_54_kawin _lk',
        '50_54_kawin_pr',
        '50_54_cerai_hidup_lk',
        '50_54_cerai_hidup_pr',
        '50_54_cerai_mati_lk',
        '50_54_cerai_mati_pr',
        '55_59_belum_kawin_lk',
        '55_59_belum_kawin_pr',
        '55_59_kawin_lk',
        '55_59_kawin_pr',
        '55_59_cerai_hidup_lk',
        '55_59_cerai_hidup_pr',
        '55_59_cerai_mati_lk',
        '55_59_cerai_mati_pr',
        '60_64_belum_kawin_lk',
        '60_64_belum_kawin_pr',
        '60_64_kawin_lk',
        '60_64_kawin_pr',
        '60_64_cerai_hidup_lk',
        '60_64_cerai_hidup_pr',
        '60_64_cerai_mati_lk',
        '60_64_cerai_mati_pr',
        '65_69_belum_kawin_lk',
        '65_69_belum_kawin_pr',
        '65_69_kawin_lk',
        '65_69_kawin_pr',
        '65_69_cerai_hidup_lk',
        '65_69_cerai_hidup_pr',
        '65_69_cerai_mati_lk',
        '65_69_cerai_mati_pr',
        '70_74_belum_kawin_lk',
        '70_74_belum_kawin_pr',
        '70_74_kawin_lk',
        '70_74_kawin_pr',
        '70_74_cerai_hidup_lk',
        '70_74_cerai_hidup_pr',
        '70_74_cerai_mati_lk',
        '70_74_cerai_mati_pr',
        'lebih_75_belum_kawin_lk',
        'lebih_75_belum_kawin_pr',
        'lebih_75_kawin_lk',
        'lebih_75_kawin_pr',
        'lebih_75_cerai_hidup_lk',
        'lebih_75_cerai_hidup_pr',
        'lebih_75_cerai_mati_lk',
        'lebih_75_cerai_mati_pr',
    ],
    'categoryMarriageStatus' => [
        'belum_kawin_lk',
        'belum_kawin_pr',
        'kawin_lk',
        'kawin_pr',
        'cerai_hidup_lk',
        'cerai_hidup_pr',
        'cerai_mati_lk',
        'cerai_mati_pr',
    ]
];
