<?php

return [
    'dataDashboard' => [
        'semester' => '2',
        'tahun' => '2024'
    ],
    'listFileImport' => [
        '1' => 'App\Imports\DisabilitasJenisKelaminImport',
        '2' => 'App\Imports\DisabilitasPekerjaanImport',
        '3' => 'App\Imports\DisabilitasPendidikanImport',
        '4' => 'App\Imports\KepalaKeluargaJenisKelaminImport',
        '5' => 'App\Imports\KepalaKeluargaAgamaImport',
        '6' => 'App\Imports\KepalaKeluargaPekerjaanImport',
        '7' => 'App\Imports\KepalaKeluargaPendidikanImport',
        '8' => 'App\Imports\KepalaKeluargaStatusKawinImport',
        '9' => 'App\Imports\PendidikanGolonganDarahImport',
        '10' => 'App\Imports\PendidikanJenisKelaminImport',
        '11' => 'App\Imports\PendudukJenisKelaminImport',
        '12' => 'App\Imports\PendudukAgamaImport',
        '13' => 'App\Imports\PendudukGolonganDarahImport',
        '14' => 'App\Imports\PendudukHubunganKeluargaImport',
        '15' => 'App\Imports\PendudukPekerjaanImport',
        '16' => 'App\Imports\KepemilikanAktaCeraiImport',
        '17' => 'App\Imports\KepemilikanAktaKawinImport',
        '18' => 'App\Imports\KepemilikanAktaKelahiranImport',
        '19' => 'App\Imports\KepemilikanKartuKeluargaImport',
        '20' => 'App\Imports\KepemilikanKIAImport',
        '21' => 'App\Imports\KepemilikanAktaCeraiAgamaImport',
        '22' => 'App\Imports\KepemilikanAktaAgamaKawinImport',
        '23' => 'App\Imports\StrukturUmurAgamaKelompokUmurImport',
        '24' => 'App\Imports\StrukturUmurDisabilitasKelompokUmurImport',
        '25' => 'App\Imports\StrukturUmurDisabilitasPendidikanUmurTunggalImport',
        '26' => 'App\Imports\StrukturUmurDisabilitasUmurTunggalImport',
        '27' => 'App\Imports\StrukturUmurDisabilitasUsiaSekolahKelompokUmurImport',
        '28' => 'App\Imports\StrukturUmurGolonganDarahKelompokUmurImport',
        '29' => 'App\Imports\StrukturUmurGolonganDarahUmurTunggalImport',
        '30' => 'App\Imports\StrukturUmurKepalaKeluargaKelompokUmurImport',
        '31' => 'App\Imports\StrukturUmurKepalaKeluargaStatusKawinImport',
        '32' => 'App\Imports\StrukturUmurKepalaKeluargaUmurTunggalImport',
        '33' => 'App\Imports\StrukturUmurPendudukKelompokUmurImport',
        '34' => 'App\Imports\StrukturUmurPendudukStatusKawinKelompokUmurImport',
        '35' => 'App\Imports\StrukturUmurPendudukStatusKawinUmurTunggalImport',
        '36' => 'App\Imports\StrukturUmurPendudukUmurTunggalImport',
        '37' => 'App\Imports\StrukturUmurPendudukUsiaMudaProduktifImport',
        '38' => 'App\Imports\StrukturUmurPendudukUsiaSekolahImport',
        '39' => 'App\Imports\StatusKawinPendudukAgamaImport',
        '40' => 'App\Imports\StatusKawinPendudukJenisKelaminImport',
        '41' => 'App\Imports\StatusKawinPendudukPekerjaanImport',
        '42' => 'App\Imports\LaporanKinerjaCapilFormatPdakImport',
        '43' => 'App\Imports\LaporanKinerjaDafdukFormatPdakImport',
        '44' => 'App\Imports\PendidikanPekerjaanImport',
        '45' => 'App\Imports\KepemilikanKtpImport',

    ],
    'listFileModel' => [
        '1' => 'App\Models\AgregatDKB\Disabilitas\JenisKelamin',
        '2' => 'App\Models\AgregatDKB\Disabilitas\Pekerjaan',
        '3' => 'App\Models\AgregatDKB\Disabilitas\Pendidikan',
        '4' => 'App\Models\AgregatDKB\KepalaKeluarga\JenisKelamin',
        '5' => 'App\Models\AgregatDKB\KepalaKeluarga\Agama',
        '6' => 'App\Models\AgregatDKB\KepalaKeluarga\Pekerjaan',
        '7' => 'App\Models\AgregatDKB\KepalaKeluarga\Pendidikan',
        '8' => 'App\Models\AgregatDKB\KepalaKeluarga\StatusKawin',
        '9' => 'App\Models\AgregatDKB\Pendidikan\GolonganDarah',
        '10' => 'App\Models\AgregatDKB\Pendidikan\JenisKelamin',
        '11' => 'App\Models\AgregatDKB\Penduduk\JenisKelamin',
        '12' => 'App\Models\AgregatDKB\Penduduk\Agama',
        '13' => 'App\Models\AgregatDKB\Penduduk\GolonganDarah',
        '14' => 'App\Models\AgregatDKB\Penduduk\HubunganKeluarga',
        '15' => 'App\Models\AgregatDKB\Penduduk\Pekerjaan',
        '16' => 'App\Models\Kepemilikan\AktaCerai',
        '17' => 'App\Models\Kepemilikan\AktaKawin',
        '18' => 'App\Models\Kepemilikan\AktaKelahiran',
        '19' => 'App\Models\Kepemilikan\KartuKeluarga',
        '20' => 'App\Models\Kepemilikan\KIA',
        '21' => 'App\Models\Kepemilikan\AktaCeraiAgama',
        '22' => 'App\Models\Kepemilikan\AktaKawinAgama',
        '23' => 'App\Models\StrukturUmur\Agama\KelompokUmur',
        '24' => 'App\Models\StrukturUmur\Disabilitas\KelompokUmur',
        '25' => 'App\Models\StrukturUmur\Disabilitas\PendidikanUmurTunggal',
        '26' => 'App\Models\StrukturUmur\Disabilitas\UmurTunggal',
        '27' => 'App\Models\StrukturUmur\Disabilitas\UsiaSekolahKelompokUmur',
        '28' => 'App\Models\StrukturUmur\GolonganDarah\KelompokUmur',
        '29' => 'App\Models\StrukturUmur\GolonganDarah\UmurTunggal',
        '30' => 'App\Models\StrukturUmur\KepalaKeluarga\KelompokUmur',
        '31' => 'App\Models\StrukturUmur\KepalaKeluarga\StatusKawin',
        '32' => 'App\Models\StrukturUmur\KepalaKeluarga\UmurTunggal',
        '33' => 'App\Models\StrukturUmur\Penduduk\KelompokUmur',
        '34' => 'App\Models\StrukturUmur\Penduduk\StatusKawinKelompokUmur',
        '35' => 'App\Models\StrukturUmur\Penduduk\StatusKawinUmurTunggal',
        '36' => 'App\Models\StrukturUmur\Penduduk\UmurTunggal',
        '37' => 'App\Models\StrukturUmur\Penduduk\UsiaMudaProduktif',
        '38' => 'App\Models\StrukturUmur\Penduduk\UsiaSekolah',
        '39' => 'App\Models\AgregatDKB\StatusKawin\Agama',
        '40' => 'App\Models\AgregatDKB\StatusKawin\JenisKelamin',
        '41' => 'App\Models\AgregatDKB\StatusKawin\Pekerjaan',
        '42' => 'App\Models\LaporanKinerjaFormatPdak\Capil',
        '43' => 'App\Models\LaporanKinerjaFormatPdak\Dafduk',
        '44' => 'App\Models\AgregatDKB\Pendidikan\Pekerjaan',
        '45' => 'App\Models\Kepemilikan\Ktp'
    ],
    'listCalculateDataFunction' => [
        'CV8V59hUCF' => 'dataPendudukJenisKelamin',
        'MupFCfSa6a' => 'dataPendudukAgama',
        'aPH7zF09S1' => 'dataPendudukGoldar',
        'bfl4aaeCTi' => 'dataPendudukHubKel',
        'fFKZKP7AnA' => 'dataPendudukPekerjaan',
        'nYtZCUxdr6' =>  'dataKepalaKeluargaAgama',
        'MNJiVyMrxR' =>  'dataKepalaKeluargaJenisKelamin',
        'gblPf8pfSp' =>  'dataKepalaKeluargaPendidikan',
        'aQIpF1uiEO' =>  'dataKepalaKeluargaPekerjaan',
        'ZvGL0vPJLC' =>  'dataKelapaKeluargaStatusKawin',
        '2XSDKgCQJH' =>  'dataStatusKawinAgama',
        'oqhOV9WfkB' =>  'dataStatusKawinJenisKelamin',
        'AWn2KmOLao' =>  'dataStatusKawinPekerjaan',
        'XYPtrXHZkf' =>  'dataPendidikanPendudukJenisKelamin',
        'eRPt22HZkf' =>  'dataPendidikanPekerjaan',
        'XYPt22HZkf' =>  'dataPendidikanGolonganDarah',
        'trg1Xxialt' =>  'dataDisabilitasJenisKelamin',
        'iXnbXnoUnq' =>  'dataDisabilitasPekerjaan',
        '8sfHKi6GHS' =>  'dataDisabilitasPendidikan',
        '6D6A18O1Hm' =>  'dataKepemilikanAktaKelahiran',
        'CJY6qXue82' =>  'dataKepemilikanAktaPerkawinan',
        'PKf3FqywDa' =>  'dataKepemilikanAktaPerkawinanAgama',
        'goKsHUTCOG' =>  'dataKepemilikanAktaCerai',
        'eCnoaOxtiS' =>  'dataKepemilikanAktaCeraiAgama',
        '2ovlKZBzGU' =>  'dataKepemilikanKia',
        '6DFxmctALZ' =>  'dataKepemilikanKartuKeluarga',
        'hsdtkgPeS5' =>  'dataKepemilikanKTP',
        'OqF8P0knI7' =>  'dataStrukturUmurAgamaKelompokUmur',
        'VtDkcpu8FN' =>  'dataStrukturUmurDisabilitasKelompokUmur',
        'nx8eUW4TWq' =>  'dataStrukturUmurDisabilitasPendidikan',
        '3WjgN9m6aS' =>  'dataStrukturUmurDisabilitasUmurTunggal',
        'FIZKE9hOxo' =>  'dataStrukturUmurDisabilitasUsiaSekolah',
        'dRgHdz0S5A' =>  'dataStrukturUmurGolonganDarahKelompokUmur',
        'eRkbPisQHv' =>  'dataStrukturUmurGolonganDarahUmurTunggal',
        'svFaBJRBLQ' =>  'dataStrukturUmurKepalaKeluargaKelompokUmur',
        'lo4z2cDrRC' =>  'dataStrukturUmurKepalaKeluargaUmurTunggal',
        'EJpy2qXC3z' =>  'dataStrukturUmurKepalaKeluargaStatusKawin',
        'Byxp2PxZK2' =>  'dataStrukturUmurPendudukUmurTunggal',
        '4riLDLsE6q' =>  'dataStrukturUmurPendudukStatuKawinUmurTunggal',
        'gWNOWEQuYC' =>  'dataSturukUmurPendudukKelompokUmur',
        'RIvQj7G1XZ' =>  'dataStrukturUmurPendudukStatusKawinKelompokUmur',
        'ObqRhsP78G' =>  'dataStrukturUmurPendudukUsiaSekolah',
        '7fKa0gsKtH' =>  'dataStrukturUmurPendudukUsiaMudaProduktifTua',
        'aB3x9LpQrT' =>  'laporanKinerjaPdakCapil',
        '7yZk8WvNmD' =>  'laporanKinerjaPdakDafduk',
        'kP9mY2qR7s' =>  'dataPelayananOnline',
        '7fK97qB2ax' =>  'dataCetakEktp',
        '7x9Fk2pQ8R' =>  'dataPerekaman',
        '7fGk2pQ9Lm' => 'dateRangeAgeDisabilitasPendidikan',
    ],
    'categoryEducationDisabilites' => [
        'fisik_tidak_belum_sekolah_l',
        'fisik_tidak_belum_sekolah_p',
        'fisik_tidak_belum_sekolah_jml',
        'netra_tidak_belum_sekolah_l',
        'netra_tidak_belum_sekolah_p',
        'netra_tidak_belum_sekolah_jml',
        'rungu_tidak_belum_sekolah_l',
        'rungu_tidak_belum_sekolah_p',
        'rungu_tidak_belum_sekolah_jml',
        'mental_jiwa_tidak_belum_sekolah_l',
        'mental_jiwa_tidak_belum_sekolah_p',
        'mental_jiwa_tidak_belum_sekolah_jml',
        'fisik_mental_tidak_belum_sekolah_l',
        'fisik_mental_tidak_belum_sekolah_p',
        'fisik_mental_tidak_belum_sekolah_jml',
        'lainnya_tidak_belum_sekolah_l',
        'lainnya_tidak_belum_sekolah_p',
        'lainnya_tidak_belum_sekolah_jml',
        'fisik_belum_tamat_sd_sederajat_l',
        'fisik_belum_tamat_sd_sederajat_p',
        'fisik_belum_tamat_sd_sederajat_jml',
        'netra_belum_tamat_sd_sederajat_l',
        'netra_belum_tamat_sd_sederajat_p',
        'netra_belum_tamat_sd_sederajat_jml',
        'rungu_belum_tamat_sd_sederajat_l',
        'rungu_belum_tamat_sd_sederajat_p',
        'rungu_belum_tamat_sd_sederajat_jml',
        'mental_jiwa_belum_tamat_sd_sederajat_l',
        'mental_jiwa_belum_tamat_sd_sederajat_p',
        'mental_jiwa_belum_tamat_sd_sederajat_jml',
        'fisik_mental_belum_tamat_sd_sederajat_l',
        'fisik_mental_belum_tamat_sd_sederajat_p',
        'fisik_mental_belum_tamat_sd_sederajat_jml',
        'lainnya_belum_tamat_sd_sederajat_l',
        'lainnya_belum_tamat_sd_sederajat_p',
        'lainnya_belum_tamat_sd_sederajat_jml',
        'fisik_tamat_sd_sederajat_l',
        'fisik_tamat_sd_sederajat_p',
        'fisik_tamat_sd_sederajat_jml',
        'netra_tamat_sd_sederajat_l',
        'netra_tamat_sd_sederajat_p',
        'netra_tamat_sd_sederajat_jml',
        'rungu_tamat_sd_sederajat_l',
        'rungu_tamat_sd_sederajat_p',
        'rungu_tamat_sd_sederajat_jml',
        'mental_jiwa_tamat_sd_sederajat_l',
        'mental_jiwa_tamat_sd_sederajat_p',
        'mental_jiwa_tamat_sd_sederajat_jml',
        'fisik_mental_tamat_sd_sederajat_l',
        'fisik_mental_tamat_sd_sederajat_p',
        'fisik_mental_tamat_sd_sederajat_jml',
        'lainnya_tamat_sd_sederajat_l',
        'lainnya_tamat_sd_sederajat_p',
        'lainnya_tamat_sd_sederajat_jml',
        'fisik_sltp_sederajat_l',
        'fisik_sltp_sederajat_p',
        'fisik_sltp_sederajat_jml',
        'netra_sltp_sederajat_l',
        'netra_sltp_sederajat_p',
        'netra_sltp_sederajat_jml',
        'rungu_sltp_sederajat_l',
        'rungu_sltp_sederajat_p',
        'rungu_sltp_sederajat_jml',
        'mental_jiwa_sltp_sederajat_l',
        'mental_jiwa_sltp_sederajat_p',
        'mental_jiwa_sltp_sederajat_jml',
        'fisik_mental_sltp_sederajat_l',
        'fisik_mental_sltp_sederajat_p',
        'fisik_mental_sltp_sederajat_jml',
        'lainnya_sltp_sederajat_l',
        'lainnya_sltp_sederajat_p',
        'lainnya_sltp_sederajat_jml',
        'fisik_slta_sederajat_l',
        'fisik_slta_sederajat_p',
        'fisik_slta_sederajat_jml',
        'netra_slta_sederajat_l',
        'netra_slta_sederajat_p',
        'netra_slta_sederajat_jml',
        'rungu_slta_sederajat_l',
        'rungu_slta_sederajat_p',
        'rungu_slta_sederajat_jml',
        'mental_slta_sederajat_l',
        'mental_slta_sederajat_p',
        'mental_jiwa_slta_sederajat_jml',
        'fisik_mental_slta_sederajat_l',
        'fisik_mental_slta_sederajat_p',
        'fisik_mental_slta_sederajat_jml',
        'lainnya_slta_sederajat_l',
        'lainnya_slta_sederajat_p',
        'lainnya_slta_sederajat_jml',
        'fisik_diploma_i_ii_l',
        'fisik_diploma_i_ii_p',
        'fisik_diploma_i_ii_jml',
        'netra_diploma_i_ii_l',
        'netra_diploma_i_ii_p',
        'netra_diploma_i_ii_jml',
        'rungu_diploma_i_ii_l',
        'rungu_diploma_i_ii_p',
        'rungu_diploma_i_ii_jml',
        'mental_jiwa_diploma_i_ii_l',
        'mental_jiwa_diploma_i_ii_p',
        'mental_jiwa_diploma_i_ii_jml',
        'fisik_mental_diploma_i_ii_l',
        'fisik_mental_diploma_i_ii_p',
        'fisik_mental_diploma_i_ii_jml',
        'lainnya_diploma_i_ii_l',
        'lainnya_diploma_i_ii_p',
        'lainnya_diploma_i_ii_jml',
        'fisik_akademi_diploma_iii_s_muda_l',
        'fisik_akademi_diploma_iii_s_muda_p',
        'fisik_akademi_diploma_iii_s_muda_jml',
        'netra_akademi_diploma_iii_s_muda_l',
        'netra_akademi_diploma_iii_s_muda_p',
        'netra_akademi_diploma_iii_s_muda_jml',
        'rungu_akademi_diploma_iii_s_muda_l',
        'rungu_akademi_diploma_iii_s_muda_p',
        'rungu_akademi_diploma_iii_s_muda_jml',
        'mental_jiwa_akademi_diploma_iii_s_muda_l',
        'mental_jiwa_akademi_diploma_iii_s_muda_p',
        'mental_jiwa_akademi_diploma_iii_s_muda_jml',
        'fisik_mental_akademi_diploma_iii_s_muda_l',
        'fisik_mental_akademi_diploma_iii_s_muda_p',
        'fisik_mental_akademi_diploma_iii_s_muda_jml',
        'lainnya_akademi_diploma_iii_s_muda_l',
        'lainnya_akademi_diploma_iii_s_muda_p',
        'lainnya_akademi_diploma_iii_s_muda_jml',
        'fisik_diploma_iv_l',
        'fisik_diploma_iv_p',
        'fisik_diploma_iv_jml',
        'netra_diploma_iv_l',
        'netra_diploma_iv_p',
        'netra_diploma_iv_jml',
        'rungu_diploma_iv_l',
        'rungu_diploma_iv_p',
        'rungu_diploma_iv_jml',
        'mental_jiwa_diploma_iv_l',
        'mental_jiwa_diploma_iv_p',
        'mental_jiwa_diploma_iv_jml',
        'fisik_mental_diploma_iv_l',
        'fisik_mental_diploma_iv_p',
        'fisik_mental_diploma_iv_jml',
        'lainnya_diploma_iv_l',
        'lainnya_diploma_iv_p',
        'lainnya_diploma_iv_jml',
        'fisik_strata_ii_l',
        'fisik_strata_ii_p',
        'fisik_strata_ii_jml',
        'netra_strata_ii_l',
        'netra_strata_ii_p',
        'netra_strata_ii_jml',
        'rungu_strata_ii_l',
        'rungu_strata_ii_p',
        'rungu_strata_ii_jml',
        'mental_jiwa_strata_ii_l',
        'mental_jiwa_strata_ii_p',
        'mental_jiwa_strata_ii_jml',
        'fisik_mental_strata_ii_l',
        'fisik_mental_strata_ii_p',
        'fisik_mental_strata_ii_jml',
        'lainnya_strata_ii_l',
        'lainnya_strata_ii_p',
        'lainnya_strata_ii_jml',
        'fisik_strata_iii_l',
        'fisik_strata_iii_p',
        'fisik_strata_iii_jml',
        'netra_strata_iii_l',
        'netra_strata_iii_p',
        'netra_strata_iii_jml',
        'rungu_strata_iii_l',
        'rungu_strata_iii_p',
        'rungu_strata_iii_jml',
        'mental_jiwa_strata_iii_l',
        'mental_jiwa_strata_iii_p',
        'mental_jiwa_strata_iii_jml',
        'fisik_mental_strata_iii_l',
        'fisik_mental_strata_iii_p',
        'fisik_mental_strata_iii_jml',
        'lainnya_strata_iii_l',
        'lainnya_strata_iii_p',
        'lainnya_strata_iii_jml',
    ],
    'categoryDisabilities' => [
        'disabilitas_fisik_lk',
        'disabilitas_fisik_pr',
        'disabilitas_fisik_jml',
        'disabilitas_netra_buta_lk',
        'disabilitas_netra_buta_pr',
        'disabilitas_netra_buta_jml',
        'disabilitas_rungu_wicara_lk',
        'disabilitas_rungu_wicara_pr',
        'disabilitas_rungu_wicara_jml',
        'disabilitas_mental_jiwa_lk',
        'disabilitas_mental_jiwa_pr',
        'disabilitas_mental_jiwa_jml',
        'disabilitas_fisik_mental_lk',
        'disabilitas_fisik_mental_pr',
        'disabilitas_fisik_mental_jml',
        'disabilitas_lainnya_lk',
        'disabilitas_lainnya_pr',
        'disabilitas_lainnya_jml',
    ],
    'categoryAgeSchollDisabilities' => [
        'fisik_u4_6th_lk',
        'fisik_u4_6th_pr',
        'fisik_u7_12th_lk',
        'fisik_u7_12th_pr',
        'fisik_u13_15th_lk',
        'fisik_u13_15th_pr',
        'fisik_u16_18th_lk',
        'fisik_u16_18th_pr',
        'netra_buta_u4_6th_lk',
        'netra_buta_u4_6th_pr',
        'netra_buta_u7_12th_lk',
        'netra_buta_u7_12th_pr',
        'netra_buta_u13_15th_lk',
        'netra_buta_u13_15th_pr',
        'netra_buta_u16_18th_lk',
        'netra_buta_u16_18th_pr',
        'rungu_wicara_u4_6th_lk',
        'rungu_wicara_u4_6th_pr',
        'rungu_wicara_u7_12th_lk',
        'rungu_wicara_u7_12th_pr',
        'rungu_wicara_u13_15th_lk',
        'rungu_wicara_u13_15th_pr',
        'rungu_wicara_u16_18th_lk',
        'rungu_wicara_u16_18th_pr',
        'mental_jiwa_u4_6th_lk',
        'mental_jiwa_u4_6th_pr',
        'mental_jiwa_u7_12th_lk',
        'mental_jiwa_u7_12th_pr',
        'mental_jiwa_u13_15th_lk',
        'mental_jiwa_u13_15th_pr',
        'mental_jiwa_u16_18th_lk',
        'mental_jiwa_u16_18th_pr',
        'fisik_mental_u4_6th_lk',
        'fisik_mental_u4_6th_pr',
        'fisik_mental_u7_12th_lk',
        'fisik_mental_u7_12th_pr',
        'fisik_mental_u13_15th_lk',
        'fisik_mental_u13_15th_pr',
        'fisik_mental_u16_18th_lk',
        'fisik_mental_u16_18th_pr',
        'lainnya_u4_6th_lk',
        'lainnya_u4_6th_pr',
        'lainnya_u7_12th_lk',
        'lainnya_u7_12th_pr',
        'lainnya_u13_15th_lk',
        'lainnya_u13_15th_pr',
        'lainnya_u16_18th_lk',
        'lainnya_u16_18th_pr',
    ],
    'categoryBlood' => [
        'a_lk',
        'a_pr',
        'a_jml',
        'a_m_lk',
        'a_m_pr',
        'a_m_jml',
        'a_p_lk',
        'a_p_pr',
        'a_p_jml',
        'b_lk',
        'b_pr',
        'b_jml',
        'b_m_lk',
        'b_m_pr',
        'b_m_jml',
        'b_p_lk',
        'b_p_pr',
        'b_p_jml',
        'ab_lk',
        'ab_pr',
        'ab_jml',
        'ab_m_lk',
        'ab_m_pr',
        'ab_m_jml',
        'ab_p_lk',
        'ab_p_pr',
        'ab_p_jml',
        'o_lk',
        'o_pr',
        'o_jml',
        'o_m_lk',
        'o_m_pr',
        'o_m_jml',
        'o_p_lk',
        'o_p_pr',
        'o_p_jml',
        'tidak_tahu_lk',
        'tidak_tahu_pr',
        'tidak_tahu_jml',
    ],
    'categoryAgeGroup' => [
        '00_04_tahun_lk',
        '00_04_tahun_pr',
        '00_04_tahun_jml',
        '05_09_tahun_lk',
        '05_09_tahun_pr',
        '05_09_tahun_jml',
        '10_14_tahun_lk',
        '10_14_tahun_pr',
        '10_14_tahun_jml',
        '15_19_tahun_lk',
        '15_19_tahun_pr',
        '15_19_tahun_jml',
        '20_24_tahun_lk',
        '20_24_tahun_pr',
        '20_24_tahun_jml',
        '25_29_tahun_lk',
        '25_29_tahun_pr',
        '25_29_tahun_jml',
        '30_34_tahun_lk',
        '30_34_tahun_pr',
        '30_34_tahun_jml',
        '35_39_tahun_lk',
        '35_39_tahun_pr',
        '35_39_tahun_jml',
        '40_44_tahun_lk',
        '40_44_tahun_pr',
        '40_44_tahun_jml',
        '45_49_tahun_lk',
        '45_49_tahun_pr',
        '45_49_tahun_jml',
        '50_54_tahun_lk',
        '50_54_tahun_pr',
        '50_54_tahun_jml',
        '55_59_tahun_lk',
        '55_59_tahun_pr',
        '55_59_tahun_jml',
        '60_64_tahun_lk',
        '60_64_tahun_pr',
        '60_64_tahun_jml',
        '65_69_tahun_lk',
        '65_69_tahun_pr',
        '65_69_tahun_jml',
        '70_74_tahun_lk',
        '70_74_tahun_pr',
        '70_74_tahun_jml',
        'lebih_75_tahun_lk',
        'lebih_75_tahun_pr',
        'lebih_75_tahun_jml',
    ],
    'categoryAgeGroupMarriageStatus' => [
        '00_04_belum_kawin_lk',
        '00_04_belum_kawin_pr',
        '00_04_kawin_lk',
        '00_04_kawin_pr',
        '00_04_cerai_hidup_lk',
        '00_04_cerai_hidup_pr',
        '00_04_cerai_mati_lk',
        '00_04_cerai_mati_pr',
        '05_09_belum_kawin_lk',
        '05_09_belum_kawin_pr',
        '05_09_kawin_lk',
        '05_09_kawin_pr',
        '05_09_cerai_hidup_lk',
        '05_09_cerai_hidup_pr',
        '05_09_cerai_mati_lk',
        '05_09_cerai_mati_pr',
        '10_14_belum_kawin_lk',
        '10_14_belum_kawin_pr',
        '10_14_kawin_lk',
        '10_14_kawin_pr',
        '10_14_cerai_hidup_lk',
        '10_14_cerai_hidup_pr',
        '10_14_cerai_mati_lk',
        '10_14_cerai_mati_pr',
        '15_19_belum_kawin_lk',
        '15_19_belum_kawin_pr',
        '15_19_kawin_lk',
        '15_19_kawin_pr',
        '15_19_cerai_hidup_lk',
        '15_19_cerai_hidup_pr',
        '15_19_cerai_mati_lk',
        '15_19_cerai_mati_pr',
        '20_24_belum_kawin_lk',
        '20_24_belum_kawin_pr',
        '20_24_kawin_lk',
        '20_24_kawin_pr',
        '20_24_cerai_hidup_lk',
        '20_24_cerai_hidup_pr',
        '20_24_cerai_mati_lk',
        '20_24_cerai_mati_pr',
        '25_29_belum_kawin_lk',
        '25_29_belum_kawin_pr',
        '25_29_kawin_lk',
        '25_29_kawin_pr',
        '25_29_cerai_hidup_lk',
        '25_29_cerai_hidup_pr',
        '25_29_cerai_mati_lk',
        '25_29_cerai_mati_pr',
        '30_34_belum_kawin_lk',
        '30_34_belum_kawin_pr',
        '30_34_kawin_lk',
        '30_34_kawin_pr',
        '30_34_cerai_hidup_lk',
        '30_34_cerai_hidup_pr',
        '30_34_cerai_mati_lk',
        '30_34_cerai_mati_pr',
        '35_39_belum_kawin_lk',
        '35_39_belum_kawin_pr',
        '35_39_kawin_lk',
        '35_39_kawin_pr',
        '35_39_cerai_hidup_lk',
        '35_39_cerai_hidup_pr',
        '35_39_cerai_mati_lk',
        '35_39_cerai_mati_pr',
        '40_44_belum_kawin_lk',
        '40_44_belum_kawin_pr',
        '40_44_kawin_lk',
        '40_44_kawin_pr',
        '40_44_cerai_hidup_lk',
        '40_44_cerai_hidup_pr',
        '40_44_cerai_mati_lk',
        '40_44_cerai_mati_pr',
        '45_49_belum_kawin_lk',
        '45_49_belum_kawin_pr',
        '45_49_kawin_lk',
        '45_49_kawin_pr',
        '45_49_cerai_hidup_lk',
        '45_49_cerai_hidup_pr',
        '45_49_cerai_mati_lk',
        '45_49_cerai_mati_pr',
        '50_54_belum_kawin_lk',
        '50_54_belum_kawin_pr',
        '50_54_kawin_lk',
        '50_54_kawin_pr',
        '50_54_cerai_hidup_lk',
        '50_54_cerai_hidup_pr',
        '50_54_cerai_mati_lk',
        '50_54_cerai_mati_pr',
        '55_59_belum_kawin_lk',
        '55_59_belum_kawin_pr',
        '55_59_kawin_lk',
        '55_59_kawin_pr',
        '55_59_cerai_hidup_lk',
        '55_59_cerai_hidup_pr',
        '55_59_cerai_mati_lk',
        '55_59_cerai_mati_pr',
        '60_64_belum_kawin_lk',
        '60_64_belum_kawin_pr',
        '60_64_kawin_lk',
        '60_64_kawin_pr',
        '60_64_cerai_hidup_lk',
        '60_64_cerai_hidup_pr',
        '60_64_cerai_mati_lk',
        '60_64_cerai_mati_pr',
        '65_69_belum_kawin_lk',
        '65_69_belum_kawin_pr',
        '65_69_kawin_lk',
        '65_69_kawin_pr',
        '65_69_cerai_hidup_lk',
        '65_69_cerai_hidup_pr',
        '65_69_cerai_mati_lk',
        '65_69_cerai_mati_pr',
        '70_74_belum_kawin_lk',
        '70_74_belum_kawin_pr',
        '70_74_kawin_lk',
        '70_74_kawin_pr',
        '70_74_cerai_hidup_lk',
        '70_74_cerai_hidup_pr',
        '70_74_cerai_mati_lk',
        '70_74_cerai_mati_pr',
        'lebih_75_belum_kawin_lk',
        'lebih_75_belum_kawin_pr',
        'lebih_75_kawin_lk',
        'lebih_75_kawin_pr',
        'lebih_75_cerai_hidup_lk',
        'lebih_75_cerai_hidup_pr',
        'lebih_75_cerai_mati_lk',
        'lebih_75_cerai_mati_pr',
    ],
    'categoryMarriageStatus' => [
        'kawin_lk',
        'kawin_pr',
        'belum_kawin_lk',
        'belum_kawin_pr',
        'cerai_hidup_lk',
        'cerai_hidup_pr',
        'cerai_mati_lk',
        'cerai_mati_pr'
    ],
    'categoryJob' => [
        'belum_tidak_bekerja_l',
        'belum_tidak_bekerja_p',
        'mengurus_rumah_tangga_l',
        'mengurus_rumah_tangga_p',
        'pelajar_mahasiswa_l',
        'pelajar_mahasiswa_p',
        'pensiunan_l',
        'pensiunan_p',
        'pegawai_negeri_sipil_pns_l',
        'pegawai_negeri_sipil_pns_p',
        'tentara_nasional_indonesia_tni_l',
        'tentara_nasional_indonesia_tni_p',
        'kepolisian_ri_polri_l',
        'kepolisian_ri_polri_p',
        'perdagangan_l',
        'perdagangan_p',
        'petani_pekebun_l',
        'petani_pekebun_p',
        'peternak_l',
        'peternak_p',
        'nelayan_perikanan_l',
        'nelayan_perikanan_p',
        'industri_l',
        'industri_p',
        'konstruksi_l',
        'konstruksi_p',
        'transportasi_l',
        'transportasi_p',
        'karyawan_swasta_l',
        'karyawan_swasta_p',
        'karyawan_bumn_l',
        'karyawan_bumn_p',
        'karyawan_bumd_l',
        'karyawan_bumd_p',
        'karyawan_honorer_l',
        'karyawan_honorer_p',
        'buruh_harian_lepas_l',
        'buruh_harian_lepas_p',
        'buruh_tani_perkebunan_l',
        'buruh_tani_perkebunan_p',
        'buruh_nelayan_perikanan_l',
        'buruh_nelayan_perikanan_p',
        'buruh_peternakan_l',
        'buruh_peternakan_p',
        'pembantu_rumah_tangga_l',
        'pembantu_rumah_tangga_p',
        'tukang_cukur_l',
        'tukang_cukur_p',
        'tukang_listrik_l',
        'tukang_listrik_p',
        'tukang_batu_l',
        'tukang_batu_p',
        'tukang_kayu_l',
        'tukang_kayu_p',
        'tukang_sol_sepatu_l',
        'tukang_sol_sepatu_p',
        'tukang_las_pandai_besi_l',
        'tukang_las_pandai_besi_p',
        'tukang_jahit_l',
        'tukang_jahit_p',
        'tukang_gigi_l',
        'tukang_gigi_p',
        'penata_rias_l',
        'penata_rias_p',
        'penata_busana_l',
        'penata_busana_p',
        'penata_rambut_l',
        'penata_rambut_p',
        'mekanik_l',
        'mekanik_p',
        'seniman_l',
        'seniman_p',
        'tabib_l',
        'tabib_p',
        'paraji_l',
        'paraji_p',
        'perancang_busana_l',
        'perancang_busana_p',
        'penterjemah_l',
        'penterjemah_p',
        'imam_masjid_l',
        'imam_masjid_p',
        'pendeta_l',
        'pendeta_p',
        'pastor_l',
        'pastor_p',
        'wartawan_l',
        'wartawan_p',
        'ustadz_mubaligh_l',
        'ustadz_mubaligh_p',
        'juru_masak_l',
        'juru_masak_p',
        'promotor_acara_l',
        'promotor_acara_p',
        'anggota_dpr_ri_l',
        'anggota_dpr_ri_p',
        'anggota_dpd_ri_l',
        'anggota_dpd_ri_p',
        'anggota_bpk_l',
        'anggota_bpk_p',
        'presiden_l',
        'presiden_p',
        'wakil_presiden_l',
        'wakil_presiden_p',
        'anggota_mahkamah_konstitusi_l',
        'anggota_mahkamah_konstitusi_p',
        'anggota_kabinet_kementerian_l',
        'anggota_kabinet_kementerian_p',
        'duta_besar_l',
        'duta_besar_p',
        'gubernur_l',
        'gubernur_p',
        'wakil_gubernur_l',
        'wakil_gubernur_p',
        'bupati_l',
        'bupati_p',
        'wakil_bupati_l',
        'wakil_bupati_p',
        'walikota_l',
        'walikota_p',
        'wakil_walikota_l',
        'wakil_walikota_p',
        'anggota_dprd_prop_l',
        'anggota_dprd_prop_p',
        'anggota_dprd_kab_kota_l',
        'anggota_dprd_kab_kota_p',
        'dosen_l',
        'dosen_p',
        'guru_l',
        'guru_p',
        'pilot_l',
        'pilot_p',
        'pengacara_l',
        'pengacara_p',
        'notaris_l',
        'notaris_p',
        'arsitek_l',
        'arsitek_p',
        'akuntan_l',
        'akuntan_p',
        'konsultan_l',
        'konsultan_p',
        'dokter_l',
        'dokter_p',
        'bidan_l',
        'bidan_p',
        'perawat_l',
        'perawat_p',
        'apoteker_l',
        'apoteker_p',
        'psikiater_psikolog_l',
        'psikiater_psikolog_p',
        'penyiar_televisi_l',
        'penyiar_televisi_p',
        'penyiar_radio_l',
        'penyiar_radio_p',
        'pelaut_l',
        'pelaut_p',
        'peneliti_l',
        'peneliti_p',
        'sopir_l',
        'sopir_p',
        'pialang_l',
        'pialang_p',
        'paranormal_l',
        'paranormal_p',
        'pedagang_l',
        'pedagang_p',
        'perangkat_desa_l',
        'perangkat_desa_p',
        'kepala_desa_l',
        'kepala_desa_p',
        'biarawan_biarawati_l',
        'biarawan_biarawati_p',
        'wiraswasta_l',
        'wiraswasta_p',
        'anggota_lembaga_tinggi_lainnya_l',
        'anggota_lembaga_tinggi_lainnya_p',
        'artis_l',
        'artis_p',
        'atlit_l',
        'atlit_p',
        'chef_l',
        'chef_p',
        'manajer_l',
        'manajer_p',
        'tenaga_tata_usaha_l',
        'tenaga_tata_usaha_p',
        'operator_l',
        'operator_p',
        'pekerja_pengolahan_kerajinan_l',
        'pekerja_pengolahan_kerajinan_p',
        'teknisi_l',
        'teknisi_p',
        'asisten_ahli_l',
        'asisten_ahli_p',
        'pekerjaan_lainnya_l',
        'pekerjaan_lainnya_p',
    ],
    'categoryEducation' => [
        'tidak_blm_sekolah_l',
        'tidak_blm_sekolah_p',
        'tidak_blm_sekolah_jml',
        'belum_tamat_sd_sederajat_l',
        'belum_tamat_sd_sederajat_p',
        'belum_tamat_sd_sederajat_jml',
        'tamat_sd_sederajat_l',
        'tamat_sd_sederajat_p',
        'tamat_sd_sederajat_jml',
        'sltp_sederajat_l',
        'sltp_sederajat_p',
        'sltp_sederajat_jml',
        'slta_sederajat_l',
        'slta_sederajat_p',
        'slta_sederajat_jml',
        'diploma_i_ii_l',
        'diploma_i_ii_p',
        'diploma_i_ii_jml',
        'akademi_dipl_iii_s_muda_l',
        'akademi_dipl_iii_s_muda_p',
        'akademi_dipl_iii_s_muda_jml',
        'diploma_iv_strata_i_l',
        'diploma_iv_strata_i_p',
        'diploma_iv_strata_i_jml',
        'strata_ii_l',
        'strata_ii_p',
        'strata_ii_jml',
        'strata_iii_l',
        'strata_iii_p',
        'strata_iii_jml',
    ],
    'categoryReligious' => [
        'islam_lk',
        'islam_pr',
        'islam_jml',
        'katholik_lk',
        'katholik_pr',
        'katholik_jml',
        'kristen_lk',
        'kristen_pr',
        'kristen_jml',
        'hindu_lk',
        'hindu_pr',
        'hindu_jml',
        'budha_lk',
        'budha_pr',
        'budha_jml',
        'konghucu_lk',
        'konghucu_pr',
        'konghucu_jml',
        'kepercayaan_lk',
        'kepercayaan_pr',
        'kepercayaan_jml',
    ],
    'categoryReligiosOwnerShip' => [
        'islam_memiliki_lk',
        'islam_memiliki_pr',
        'islam_memiliki_jml',
        'islam_blm_memiliki_jml',
        'kristen_memiliki_lk',
        'kristen_memiliki_pr',
        'kristen_memiliki_jml',
        'kristen_blm_memiliki_jml',
        'katholik_memiliki_lk',
        'katholik_memiliki_pr',
        'katholik_memiliki_jml',
        'katholik_blm_memiliki_jml',
        'hindu_memiliki_lk',
        'hindu_memiliki_pr',
        'hindu_memiliki_jml',
        'hindu_blm_memiliki_jml',
        'budha_memiliki_lk',
        'budha_memiliki_pr',
        'budha_memiliki_jml',
        'budha_blm_memiliki_jml',
        'khonghucu_memiliki_lk',
        'khonghucu_memiliki_pr',
        'khonghucu_memiliki_jml',
        'khonghucu_blm_memiliki_jml',
        'kepercayaan_memiliki_lk',
        'kepercayaan_memiliki_pr',
        'kepercayaan_memiliki_jml',
        'kepercayaan_blm_memiliki_jml',
    ],
    'categoryAktaKelahiranOwnerShip' => [
        'wajib_akta_awal_lk',
        'wajib_akta_awal_pr',
        'wajib_akta_awal_jml',
        'memiliki_awal_lk',
        'memiliki_awal_pr',
        'memiliki_awal_jml',
        'belum_memiliki_awal_lk',
        'belum_memiliki_awal_pr',
        'belum_memiliki_awal_jml',
        'usia_lebih_dari_target_lk',
        'usia_lebih_dari_target_pr',
        'usia_lebih_dari_target_jml',
        'meninggal_lk',
        'meninggal_pr',
        'meninggal_jml',
        'nonaktif_lk',
        'nonaktif_pr',
        'nonaktif_jml',
        'pindah_lk',
        'pindah_pr',
        'pindah_jml',
        'datang_lk',
        'datang_pr',
        'datang_jml',
        'hapus_operator_lk',
        'hapus_operator_pr',
        'hapus_operator_jml',
        'terbit_akta_baru_dalam_dkb_lk',
        'terbit_akta_baru_dalam_dkb_pr',
        'terbit_akta_baru_dalam_dkb_jml',
        'terbit_akta_baru_luar_dkb_lk',
        'terbit_akta_baru_luar_dkb_pr',
        'terbit_akta_baru_luar_dkb_jml',
        'wajib_akta_dinamis_lk',
        'wajib_akta_dinamis_pr',
        'wajib_akta_dinamis_jml',
        'memiliki_dinamis_lk',
        'memiliki_dinamis_pr',
        'memiliki_dinamis_jml',
        'belum_memiliki_dinamis_lk',
        'belum_memiliki_dinamis_pr',
        'belum_memiliki_dinamis_jml',
        'penambahan_lk',
        'penambahan_pr',
        'penambahan_jml',
    ],
    'categoryKiaOwnerShip' => [
        'jumlah_awal_lk',
        'jumlah_awal_pr',
        'jumlah_awal_jml',
        'memiliki_awal_lk',
        'memiliki_awal_pr',
        'memiliki_awal_jml',
        'belum_memiliki_awal_lk',
        'belum_memiliki_awal_pr',
        'belum_memiliki_awal_jml',
        'usia_lebih_target_lk',
        'usia_lebih_target_pr',
        'usia_lebih_target_jml',
        'meninggal_lk',
        'meninggal_pr',
        'meninggal_jml',
        'nonaktif_lk',
        'nonaktif_pr',
        'nonaktif_jml',
        'memiliki_dalam_dkb_lk',
        'memiliki_dalam_dkb_pr',
        'memiliki_dalam_dkb_jml',
        'memiliki_luar_dkb_lk',
        'memiliki_luar_dkb_pr',
        'memiliki_luar_dkb_jml',
        'jumlah_dinamis_lk',
        'jumlah_dinamis_pr',
        'jumlah_dinamis_ttl',
        'memiliki_dinamis_lk',
        'memiliki_dinamis_pr',
        'memiliki_dinamis_jml',
        'belum_memiliki_dinamis_lk',
        'belum_memiliki_dinamis_pr',
        'belum_memiliki_dinamis_jml',
        'penambahan_lk',
        'penambahan_pr',
        'penambahan_jml',
    ],
    'categoryRelationshipFamily' => [
        "kepala_keluarga_l",
        "kepala_keluarga_p",
        "kepala_keluarga_jml",
        "suami_l",
        "suami_p",
        "suami_jml",
        "isteri_l",
        "isteri_p",
        "isteri_jml",
        "anak_l",
        "anak_p",
        "anak_jml",
        "menantu_l",
        "menantu_p",
        "menantu_jml",
        "cucu_l",
        "cucu_p",
        "cucu_jml",
        "orang_tua_l",
        "orang_tua_p",
        "orang_tua_jml",
        "mertua_l",
        "mertua_p",
        "mertua_jml",
        "famili_lain_l",
        "famili_lain_p",
        "famili_lain_jml",
        "pembantu_l",
        "pembantu_p",
        "pembantu_jml",
        "lainnya_l",
        "lainnya_p",
        "lainnya_jml",
    ],
    'listDataFileExcelFormatImport' => [
        [
            "name_file" => "Penduduk Agama",
            "location_file" => "/format_file_excel_import/penduduk_agama.xlsx"
        ],
        [
            "name_file" => "Penduduk Golongan Darah",
            "location_file" => "/format_file_excel_import/penduduk_golongan_darah.xlsx"
        ],
        [
            "name_file" => "Penduduk Jenis Kelamin",
            "location_file" => "/format_file_excel_import/penduduk_jenis_kelamin.xlsx"
        ],
        [
            "name_file" => "Penduduk Pekerjaan",
            "location_file" => "/format_file_excel_import/penduduk_pekerjaan.xlsx"
        ],
        [
            "name_file" => "Penduduk Hubungan Keluarga",
            "location_file" => "/format_file_excel_import/penduduk_hubungan_keluarga.xlsx"
        ],
        [
            "name_file" => "Kepala Keluraga Agama",
            "location_file" => "/format_file_excel_import/kepala_keluarga_agama.xlsx"
        ],
        [
            "name_file" => "Kepala Keluraga Jenis Kelamin",
            "location_file" => "/format_file_excel_import/kepala_keluarga_jenis_kelamin.xlsx"
        ],
        [
            "name_file" => "Kepala Keluraga Pendidikan",
            "location_file" => "/format_file_excel_import/kepala_keluarga_pendidikan.xlsx"
        ],
        [
            "name_file" => "Kepala Keluraga Pekerjaan",
            "location_file" => "/format_file_excel_import/kepala_keluarga_pekerjaan.xlsx"
        ],
        [
            "name_file" => "Kepala Keluarga Status Kawin",
            "location_file" => "/format_file_excel_import/kepala_keluarga_status_kawin.xlsx"
        ],
        [
            "name_file" => "Status Kawin Agama",
            "location_file" => "/format_file_excel_import/status_kawin_agama.xlsx"
        ],
        [
            "name_file" => "Status Kawin Jenis Kelamin",
            "location_file" => "/format_file_excel_import/status_kawin_jenis_kelamin.xlsx"
        ],
        [
            "name_file" => "Status Kawin Pekerjaan",
            "location_file" => "/format_file_excel_import/status_kawin_pekerjaan.xlsx"
        ],
        [
            "name_file" => "Pendidikan Jenis Kelamin",
            "location_file" => "/format_file_excel_import/pendidikan_jenis_kelamin.xlsx"
        ],
        [
            "name_file" => "Pendidikan Pekerjaan",
            "location_file" => "/format_file_excel_import/pendidikan_pekerjaan.xlsx"
        ],
        [
            "name_file" => "Pendidikan Golongan Darah",
            "location_file" => "/format_file_excel_import/pendidikan_golongan_darah.xlsx"
        ],
        [
            "name_file" => "Disabilitas Jenis Kelamin",
            "location_file" => "/format_file_excel_import/disabilitas_jenis_kelamin.xlsx"
        ],
        [
            "name_file" => "Disabilitas Pekerjaan",
            "location_file" => "/format_file_excel_import/disabilitas_pekerjaan.xlsx"
        ],
        [
            "name_file" => "Disabilitas Pendidikan",
            "location_file" => "/format_file_excel_import/disabilitas_pendidikan.xlsx"
        ],
        [
            "name_file" => "Kepmilikan Akta Kelahiran",
            "location_file" => "/format_file_excel_import/kepemilikan_akta_kelahiran.xlsx"
        ],
        [
            "name_file" => "Kepmilikan Akta Perkawinan",
            "location_file" => "/format_file_excel_import/kepemilikan_akta_kawin.xlsx"
        ],
        [
            "name_file" => "Kepmilikan Akta Perkawinan - Agama",
            "location_file" => "/format_file_excel_import/kepemilikan_akta_kawin_agama.xlsx"
        ],
        [
            "name_file" => "Kepmilikan Akta Perceraian",
            "location_file" => "/format_file_excel_import/kepemilikan_akta_cerai.xlsx"
        ],
        [
            "name_file" => "Kepmilikan Akta Perceraian - Agama",
            "location_file" => "/format_file_excel_import/kepemilikan_akta_cerai_agama.xlsx"
        ],
        [
            "name_file" => "Kepmilikan KIA",
            "location_file" => "/format_file_excel_import/kepemilikan_kia.xlsx"
        ],
        [
            "name_file" => "Kepmilikan Kartu Keluarga",
            "location_file" => "/format_file_excel_import/kepemilikan_kartu_keluarga.xlsx"
        ],
        [
            "name_file" => "Kepmilikan KTP",
            "location_file" => "/format_file_excel_import/kepemilikan_ktp.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Agama Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_agama_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Disabilitas Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_disabilitas_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Disabilitas Pendidikan Umur Tunggal",
            "location_file" => "/format_file_excel_import/struktur_umur_disabilitas_pendidikan_umur_tunggal.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Disabilitas Umur Tunggal",
            "location_file" => "/format_file_excel_import/struktur_umur_disabilitas_umur_tunggal.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Disabilitas Usia Sekolah",
            "location_file" => "/format_file_excel_import/struktur_umur_disabilitas_usia_sekolah.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Golongan Darah Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_golongan_darah_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Golongan Darah Umur Tunggal",
            "location_file" => "/format_file_excel_import/struktur_umur_golongan_darah_umur_tunggal.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Kepala Keluarga Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_kepala_keluarga_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Kepala Keluarga Umur Tunggal",
            "location_file" => "/format_file_excel_import/struktur_umur_kepala_keluarga_umur_tunggal.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Kepala Keluarga Status Kawin Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_kepala_keluarga_status_kawin_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Penduduk Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_penduduk_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Penduduk Status Kawin Kelompok Umur",
            "location_file" => "/format_file_excel_import/struktur_umur_penduduk_status_kawin_kelompok_umur.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Penduduk Umur Tunggal",
            "location_file" => "/format_file_excel_import/struktur_umur_penduduk_umur_tunggal.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Penduduk Status Kawin Umur Tunggal",
            "location_file" => "/format_file_excel_import/struktur_umur_penduduk_status_kawin_umur_tunggal.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Penduduk Usia Sekolah",
            "location_file" => "/format_file_excel_import/struktur_umur_penduduk_usia_sekolah.xlsx"
        ],
        [
            "name_file" => "Struktur Umur Penduduk Demografi Usia",
            "location_file" => "/format_file_excel_import/struktur_umur_penduduk_demografi_usia.xlsx"
        ],
    ]
];
