<?php

namespace App\Imports;

use App\Models\AgregatDKB\KepalaKeluarga\Pekerjaan;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Illuminate\Support\Str;


class KepalaKeluargaPekerjaanImport implements ToModel, WithHeadingRow
{
    protected $tahun;
    protected $semester;

    public function __construct($tahun, $semester)
    {
        $this->tahun = $tahun;
        $this->semester = $semester;
    }

    public function model(array $row)
    {
        return new Pekerjaan([
            'uuid' => Str::uuid(),
            'semester' => $this->semester,
            'tahun' => $this->tahun,
            'kode_wilayah' => $row['kode_wilayah'],
            'BELUM_TIDAK_BEKERJA_L' => $row['BELUM_TIDAK_BEKERJA_L'],
            'BELUM_TIDAK_BEKERJA_P' => $row['BELUM_TIDAK_BEKERJA_P'],
            'MENGURUS_RUMAH_TANGGA_L' => $row['MENGURUS_RUMAH_TANGGA_L'],
            'MENGURUS_RUMAH_TANGGA_P' => $row['MENGURUS_RUMAH_TANGGA_P'],
            'PELAJAR_MAHASISWA_L' => $row['PELAJAR_MAHASISWA_L'],
            'PELAJAR_MAHASISWA_P' => $row['PELAJAR_MAHASISWA_P'],
            'PENSIUNAN_L' => $row['PENSIUNAN_L'],
            'PENSIUNAN_P' => $row['PENSIUNAN_P'],
            'PEGAWAI_NEGERI_SIPIL_PNS_L' => $row['PEGAWAI_NEGERI_SIPIL_PNS_L'],
            'PEGAWAI_NEGERI_SIPIL_PNS_P' => $row['PEGAWAI_NEGERI_SIPIL_PNS_P'],
            'TENTARA_NASIONAL_INDONESIA_TNI_L' => $row['TENTARA_NASIONAL_INDONESIA_TNI_L'],
            'TENTARA_NASIONAL_INDONESIA_TNI_P' => $row['TENTARA_NASIONAL_INDONESIA_TNI_P'],
            'KEPOLISIAN_RI_POLRI_L' => $row['KEPOLISIAN_RI_POLRI_L'],
            'KEPOLISIAN_RI_POLRI_P' => $row['KEPOLISIAN_RI_POLRI_P'],
            'PERDAGANGAN_L' => $row['PERDAGANGAN_L'],
            'PERDAGANGAN_P' => $row['PERDAGANGAN_P'],
            'PETANI_PEKEBUN_L' => $row['PETANI_PEKEBUN_L'],
            'PETANI_PEKEBUN_P' => $row['PETANI_PEKEBUN_P'],
            'PETERNAK_L' => $row['PETERNAK_L'],
            'PETERNAK_P' => $row['PETERNAK_P'],
            'NELAYAN_PERIKANAN_L' => $row['NELAYAN_PERIKANAN_L'],
            'NELAYAN_PERIKANAN_P' => $row['NELAYAN_PERIKANAN_P'],
            'INDUSTRI_L' => $row['INDUSTRI_L'],
            'INDUSTRI_P' => $row['INDUSTRI_P'],
            'KONSTRUKSI_L' => $row['KONSTRUKSI_L'],
            'KONSTRUKSI_P' => $row['KONSTRUKSI_P'],
            'TRANSPORTASI_L' => $row['TRANSPORTASI_L'],
            'TRANSPORTASI_P' => $row['TRANSPORTASI_P'],
            'KARYAWAN_SWASTA_L' => $row['KARYAWAN_SWASTA_L'],
            'KARYAWAN_SWASTA_P' => $row['KARYAWAN_SWASTA_P'],
            'KARYAWAN_BUMN_L' => $row['KARYAWAN_BUMN_L'],
            'KARYAWAN_BUMN_P' => $row['KARYAWAN_BUMN_P'],
            'KARYAWAN_BUMD_L' => $row['KARYAWAN_BUMD_L'],
            'KARYAWAN_BUMD_P' => $row['KARYAWAN_BUMD_P'],
            'KARYAWAN_HONORER_L' => $row['KARYAWAN_HONORER_L'],
            'KARYAWAN_HONORER_P' => $row['KARYAWAN_HONORER_P'],
            'BURUH_HARIAN_LEPAS_L' => $row['BURUH_HARIAN_LEPAS_L'],
            'BURUH_HARIAN_LEPAS_P' => $row['BURUH_HARIAN_LEPAS_P'],
            'BURUH_TANI_PERKEBUNAN_L' => $row['BURUH_TANI_PERKEBUNAN_L'],
            'BURUH_TANI_PERKEBUNAN_P' => $row['BURUH_TANI_PERKEBUNAN_P'],
            'BURUH_NELAYAN_PERIKANAN_L' => $row['BURUH_NELAYAN_PERIKANAN_L'],
            'BURUH_NELAYAN_PERIKANAN_P' => $row['BURUH_NELAYAN_PERIKANAN_P'],
            'BURUH_PETERNAKAN_L' => $row['BURUH_PETERNAKAN_L'],
            'BURUH_PETERNAKAN_P' => $row['BURUH_PETERNAKAN_P'],
            'PEMBANTU_RUMAH_TANGGA_L' => $row['PEMBANTU_RUMAH_TANGGA_L'],
            'PEMBANTU_RUMAH_TANGGA_P' => $row['PEMBANTU_RUMAH_TANGGA_P'],
            'TUKANG_CUKUR_L' => $row['TUKANG_CUKUR_L'],
            'TUKANG_CUKUR_P' => $row['TUKANG_CUKUR_P'],
            'TUKANG_LISTRIK_L' => $row['TUKANG_LISTRIK_L'],
            'TUKANG_LISTRIK_P' => $row['TUKANG_LISTRIK_P'],
            'TUKANG_BATU_L' => $row['TUKANG_BATU_L'],
            'TUKANG_BATU_P' => $row['TUKANG_BATU_P'],
            'TUKANG_KAYU_L' => $row['TUKANG_KAYU_L'],
            'TUKANG_KAYU_P' => $row['TUKANG_KAYU_P'],
            'TUKANG_SOL_SEPATU_L' => $row['TUKANG_SOL_SEPATU_L'],
            'TUKANG_SOL_SEPATU_P' => $row['TUKANG_SOL_SEPATU_P'],
            'TUKANG_LAS_PANDAI_BESI_L' => $row['TUKANG_LAS_PANDAI_BESI_L'],
            'TUKANG_LAS_PANDAI_BESI_P' => $row['TUKANG_LAS_PANDAI_BESI_P'],
            'TUKANG_JAHIT_L' => $row['TUKANG_JAHIT_L'],
            'TUKANG_JAHIT_P' => $row['TUKANG_JAHIT_P'],
            'TUKANG_GIGI_L' => $row['TUKANG_GIGI_L'],
            'TUKANG_GIGI_P' => $row['TUKANG_GIGI_P'],
            'PENATA_RIAS_L' => $row['PENATA_RIAS_L'],
            'PENATA_RIAS_P' => $row['PENATA_RIAS_P'],
            'PENATA_BUSANA_L' => $row['PENATA_BUSANA_L'],
            'PENATA_BUSANA_P' => $row['PENATA_BUSANA_P'],
            'PENATA_RAMBUT_L' => $row['PENATA_RAMBUT_L'],
            'PENATA_RAMBUT_P' => $row['PENATA_RAMBUT_P'],
            'MEKANIK_L' => $row['MEKANIK_L'],
            'MEKANIK_P' => $row['MEKANIK_P'],
            'SENIMAN_L' => $row['SENIMAN_L'],
            'SENIMAN_P' => $row['SENIMAN_P'],
            'TABIB_L' => $row['TABIB_L'],
            'TABIB_P' => $row['TABIB_P'],
            'PARAJI_L' => $row['PARAJI_L'],
            'PARAJI_P' => $row['PARAJI_P'],
            'PERANCANG_BUSANA_L' => $row['PERANCANG_BUSANA_L'],
            'PERANCANG_BUSANA_P' => $row['PERANCANG_BUSANA_P'],
            'PENTERJEMAH_L' => $row['PENTERJEMAH_L'],
            'PENTERJEMAH_P' => $row['PENTERJEMAH_P'],
            'IMAM_MASJID_L' => $row['IMAM_MASJID_L'],
            'IMAM_MASJID_P' => $row['IMAM_MASJID_P'],
            'PENDETA_L' => $row['PENDETA_L'],
            'PENDETA_P' => $row['PENDETA_P'],
            'PASTOR_L' => $row['PASTOR_L'],
            'PASTOR_P' => $row['PASTOR_P'],
            'WARTAWAN_L' => $row['WARTAWAN_L'],
            'WARTAWAN_P' => $row['WARTAWAN_P'],
            'USTADZ_MUBALIGH_L' => $row['USTADZ_MUBALIGH_L'],
            'USTADZ_MUBALIGH_P' => $row['USTADZ_MUBALIGH_P'],
            'JURU_MASAK_L' => $row['JURU_MASAK_L'],
            'JURU_MASAK_P' => $row['JURU_MASAK_P'],
            'PROMOTOR_ACARA_L' => $row['PROMOTOR_ACARA_L'],
            'PROMOTOR_ACARA_P' => $row['PROMOTOR_ACARA_P'],
            'ANGGOTA_DPR_RI_L' => $row['ANGGOTA_DPR_RI_L'],
            'ANGGOTA_DPR_RI_P' => $row['ANGGOTA_DPR_RI_P'],
            'ANGGOTA_DPD_RI_L' => $row['ANGGOTA_DPD_RI_L'],
            'ANGGOTA_DPD_RI_P' => $row['ANGGOTA_DPD_RI_P'],
            'ANGGOTA_BPK_L' => $row['ANGGOTA_BPK_L'],
            'ANGGOTA_BPK_P' => $row['ANGGOTA_BPK_P'],
            'PRESIDEN_L' => $row['PRESIDEN_L'],
            'PRESIDEN_P' => $row['PRESIDEN_P'],
            'WAKIL_PRESIDEN_L' => $row['WAKIL_PRESIDEN_L'],
            'WAKIL_PRESIDEN_P' => $row['WAKIL_PRESIDEN_P'],
            'ANGGOTA_MAHKAMAH_KONSTITUSI_L' => $row['ANGGOTA_MAHKAMAH_KONSTITUSI_L'],
            'ANGGOTA_MAHKAMAH_KONSTITUSI_P' => $row['ANGGOTA_MAHKAMAH_KONSTITUSI_P'],
            'ANGGOTA_KABINET_KEMENTRIAN_L' => $row['ANGGOTA_KABINET_KEMENTRIAN_L'],
            'ANGGOTA_KABINET_KEMENTRIAN_P' => $row['ANGGOTA_KABINET_KEMENTRIAN_P'],
            'DUTA_BESAR_L' => $row['DUTA_BESAR_L'],
            'DUTA_BESAR_P' => $row['DUTA_BESAR_P'],
            'GUBERNUR_L' => $row['GUBERNUR_L'],
            'GUBERNUR_P' => $row['GUBERNUR_P'],
            'WAKIL_GUBERNUR_L' => $row['WAKIL_GUBERNUR_L'],
            'WAKIL_GUBERNUR_P' => $row['WAKIL_GUBERNUR_P'],
            'BUPATI_L' => $row['BUPATI_L'],
            'BUPATI_P' => $row['BUPATI_P'],
            'WAKIL_BUPATI_L' => $row['WAKIL_BUPATI_L'],
            'WAKIL_BUPATI_P' => $row['WAKIL_BUPATI_P'],
            'WALIKOTA_L' => $row['WALIKOTA_L'],
            'WALIKOTA_P' => $row['WALIKOTA_P'],
            'WAKIL_WALIKOTA_L' => $row['WAKIL_WALIKOTA_L'],
            'WAKIL_WALIKOTA_P' => $row['WAKIL_WALIKOTA_P'],
            'ANGGOTA_DPRD_PROP_L' => $row['ANGGOTA_DPRD_PROP_L'],
            'ANGGOTA_DPRD_PROP_P' => $row['ANGGOTA_DPRD_PROP_P'],
            'ANGGOTA_DPRD_KAB_KOTA_L' => $row['ANGGOTA_DPRD_KAB_KOTA_L'],
            'ANGGOTA_DPRD_KAB_KOTA_P' => $row['ANGGOTA_DPRD_KAB_KOTA_P'],
            'DOSEN_L' => $row['DOSEN_L'],
            'DOSEN_P' => $row['DOSEN_P'],
            'GURU_L' => $row['GURU_L'],
            'GURU_P' => $row['GURU_P'],
            'PILOT_L' => $row['PILOT_L'],
            'PILOT_P' => $row['PILOT_P'],
            'PENGACARA_L' => $row['PENGACARA_L'],
            'PENGACARA_P' => $row['PENGACARA_P'],
            'NOTARIS_L' => $row['NOTARIS_L'],
            'NOTARIS_P' => $row['NOTARIS_P'],
            'ARSITEK_L' => $row['ARSITEK_L'],
            'ARSITEK_P' => $row['ARSITEK_P'],
            'AKUNTAN_L' => $row['AKUNTAN_L'],
            'AKUNTAN_P' => $row['AKUNTAN_P'],
            'KONSULTAN_L' => $row['KONSULTAN_L'],
            'KONSULTAN_P' => $row['KONSULTAN_P'],
            'DOKTER_L' => $row['DOKTER_L'],
            'DOKTER_P' => $row['DOKTER_P'],
            'BIDAN_L' => $row['BIDAN_L'],
            'BIDAN_P' => $row['BIDAN_P'],
            'PERAWAT_L' => $row['PERAWAT_L'],
            'PERAWAT_P' => $row['PERAWAT_P'],
            'APOTEKER_L' => $row['APOTEKER_L'],
            'APOTEKER_P' => $row['APOTEKER_P'],
            'PSIKIATER_PSIKOLOG_L' => $row['PSIKIATER_PSIKOLOG_L'],
            'PSIKIATER_PSIKOLOG_P' => $row['PSIKIATER_PSIKOLOG_P'],
            'PENYIAR_TELEVISI_L' => $row['PENYIAR_TELEVISI_L'],
            'PENYIAR_TELEVISI_P' => $row['PENYIAR_TELEVISI_P'],
            'PENYIAR_RADIO_L' => $row['PENYIAR_RADIO_L'],
            'PENYIAR_RADIO_P' => $row['PENYIAR_RADIO_P'],
            'PELAUT_L' => $row['PELAUT_L'],
            'PELAUT_P' => $row['PELAUT_P'],
            'PENELITI_L' => $row['PENELITI_L'],
            'PENELITI_P' => $row['PENELITI_P'],
            'SOPIR_L' => $row['SOPIR_L'],
            'SOPIR_P' => $row['SOPIR_P'],
            'PIALANG_L' => $row['PIALANG_L'],
            'PIALANG_P' => $row['PIALANG_P'],
            'PARANORMAL_L' => $row['PARANORMAL_L'],
            'PARANORMAL_P' => $row['PARANORMAL_P'],
            'PEDAGANG_L' => $row['PEDAGANG_L'],
            'PEDAGANG_P' => $row['PEDAGANG_P'],
            'PERANGKAT_DESA_L' => $row['PERANGKAT_DESA_L'],
            'PERANGKAT_DESA_P' => $row['PERANGKAT_DESA_P'],
            'KEPALA_DESA_L' => $row['KEPALA_DESA_L'],
            'KEPALA_DESA_P' => $row['KEPALA_DESA_P'],
            'BIARAWAN_BIARAWATI_L' => $row['BIARAWAN_BIARAWATI_L'],
            'BIARAWAN_BIARAWATI_P' => $row['BIARAWAN_BIARAWATI_P'],
            'WIRASWASTA_L' => $row['WIRASWASTA_L'],
            'WIRASWASTA_P' => $row['WIRASWASTA_P'],
            'ANGGOTA_LEMBAGA_TINGGI_LAINNYA_L' => $row['ANGGOTA_LEMBAGA_TINGGI_LAINNYA_L'],
            'ANGGOTA_LEMBAGA_TINGGI_LAINNYA_P' => $row['ANGGOTA_LEMBAGA_TINGGI_LAINNYA_P'],
            'ARTIS_L' => $row['ARTIS_L'],
            'ARTIS_P' => $row['ARTIS_P'],
            'ATLIT_L' => $row['ATLIT_L'],
            'ATLIT_P' => $row['ATLIT_P'],
            'CHEFF_L' => $row['CHEFF_L'],
            'CHEFF_P' => $row['CHEFF_P'],
            'MANAJER_L' => $row['MANAJER_L'],
            'MANAJER_P' => $row['MANAJER_P'],
            'TENAGA_TATA_USAHA_L' => $row['TENAGA_TATA_USAHA_L'],
            'TENAGA_TATA_USAHA_P' => $row['TENAGA_TATA_USAHA_P'],
            'OPERATOR_L' => $row['OPERATOR_L'],
            'OPERATOR_P' => $row['OPERATOR_P'],
            'PEKERJA_PENGOLAHAN_KERAJINAN_L'    => $row['PEKERJA_PENGOLAHAN_KERAJINAN_L'],
            'PEKERJA_PENGOLAHAN_KERAJINAN_P'    => $row['PEKERJA_PENGOLAHAN_KERAJINAN_P'],
            'TEKNISI_L' => $row['TEKNISI_L'],
            'TEKNISI_P' => $row['TEKNISI_P'],
            'ASISTEN_AHLI_L' => $row['ASISTEN_AHLI_L'],
            'ASISTEN_AHLI_P' => $row['ASISTEN_AHLI_P'],
            'PEKERJAAN_LAINNYA_L' => $row['PEKERJAAN_LAINNYA_L'],
            'PEKERJAAN_LAINNYA_P' => $row['PEKERJAAN_LAINNYA_P'],
        ]);
    }
}
