<?php

namespace App\Imports;

use App\Models\AgregatDKB\Pendidikan\Pekerjaan as PendidikanPekerjaan;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Illuminate\Support\Str;



class PendidikanPekerjaanImport implements ToModel, WithHeadingRow
{
    protected $tahun;
    protected $semester;

    public function __construct($tahun, $semester)
    {
        $this->tahun = $tahun;
        $this->semester = $semester;
    }
    public function model(array $row)
    {
        return new PendidikanPekerjaan([
            'uuid' => Str::uuid(),
            'semester' => $this->semester,
            'tahun' => $this->tahun,
            'kode_wilayah' => $row['kode_wilayah'],
            'pendidikan' => $row['pendidikan'],
            'belum_tidak_bekerja_l' => $row['belum_tidak_bekerja_l'],
            'belum_tidak_bekerja_p' => $row['belum_tidak_bekerja_p'],
            'mengurus_rumah_tangga_l' => $row['mengurus_rumah_tangga_l'],
            'mengurus_rumah_tangga_p' => $row['mengurus_rumah_tangga_p'],
            'pelajar_mahasiswa_l' => $row['pelajar_mahasiswa_l'],
            'pelajar_mahasiswa_p' => $row['pelajar_mahasiswa_p'],
            'pensiunan_l' => $row['pensiunan_l'],
            'pensiunan_p' => $row['pensiunan_p'],
            'pegawai_negeri_sipil_pns_l' => $row['pegawai_negeri_sipil_pns_l'],
            'pegawai_negeri_sipil_pns_p' => $row['pegawai_negeri_sipil_pns_p'],
            'tentara_nasional_indonesia_tni_l' => $row['tentara_nasional_indonesia_tni_l'],
            'tentara_nasional_indonesia_tni_p' => $row['tentara_nasional_indonesia_tni_p'],
            'kepolisian_ri_polri_l' => $row['kepolisian_ri_polri_l'],
            'kepolisian_ri_polri_p' => $row['kepolisian_ri_polri_p'],
            'perdagangan_l' => $row['perdagangan_l'],
            'perdagangan_p' => $row['perdagangan_p'],
            'petani_pekeubun_l' => $row['petani_pekeubun_l'],
            'petani_pekeubun_p' => $row['petani_pekeubun_p'],
            'peternaak_l' => $row['peternaak_l'],
            'peternaak_p' => $row['peternaak_p'],
            'nelayan_perikanan_l' => $row['nelayan_perikanan_l'],
            'nelayan_perikanan_p' => $row['nelayan_perikanan_p'],
            'industri_l' => $row['industri_l'],
            'industri_p' => $row['industri_p'],
            'konstruksi_l' => $row['konstruksi_l'],
            'konstruksi_p' => $row['konstruksi_p'],
            'transportasi_l' => $row['transportasi_l'],
            'transportasi_p' => $row['transportasi_p'],
            'karyawan_swasta_l' => $row['karyawan_swasta_l'],
            'karyawan_swasta_p' => $row['karyawan_swasta_p'],
            'karyawan_bumn_l' => $row['karyawan_bumn_l'],
            'karyawan_bumn_p' => $row['karyawan_bumn_p'],
            'karyawan_bumd_l' => $row['karyawan_bumd_l'],
            'karyawan_bumd_p' => $row['karyawan_bumd_p'],
            'karyawan_honorer_l' => $row['karyawan_honorer_l'],
            'karyawan_honorer_p' => $row['karyawan_honorer_p'],
            'buruh_harian_lepas_l' => $row['buruh_harian_lepas_l'],
            'buruh_harian_lepas_p' => $row['buruh_harian_lepas_p'],
            'buruh_tani_perkebunan_l' => $row['buruh_tani_perkebunan_l'],
            'buruh_tani_perkebunan_p' => $row['buruh_tani_perkebunan_p'],
            'buruh_nelayan_perikanan_l' => $row['buruh_nelayan_perikanan_l'],
            'buruh_nelayan_perikanan_p' => $row['buruh_nelayan_perikanan_p'],
            'buruh_peternaakan_l' => $row['buruh_peternaakan_l'],
            'buruh_peternaakan_p' => $row['buruh_peternaakan_p'],
            'pembantu_rumah_tangga_l' => $row['pembantu_rumah_tangga_l'],
            'pembantu_rumah_tangga_p' => $row['pembantu_rumah_tangga_p'],
            'tukang_cukur_l' => $row['tukang_cukur_l'],
            'tukang_cukur_p' => $row['tukang_cukur_p'],
            'tukang_listrik_l' => $row['tukang_listrik_l'],
            'tukang_listrik_p' => $row['tukang_listrik_p'],
            'tukang_batu_l' => $row['tukang_batu_l'],
            'tukang_batu_p' => $row['tukang_batu_p'],
            'tukang_kayu_l' => $row['tukang_kayu_l'],
            'tukang_kayu_p' => $row['tukang_kayu_p'],
            'tukang_sol_sepatul_l' => $row['tukang_sol_sepatul_l'],
            'tukang_sol_sepatul_p' => $row['tukang_sol_sepatul_p'],
            'tukang_las_pandai_besi_l' => $row['tukang_las_pandai_besi_l'],
            'tukang_las_pandai_besi_p' => $row['tukang_las_pandai_besi_p'],
            'tukang_jahit_l' => $row['tukang_jahit_l'],
            'tukang_jahit_p' => $row['tukang_jahit_p'],
            'tukang_gigi_l' => $row['tukang_gigi_l'],
            'tukang_gigi_p' => $row['tukang_gigi_p'],
            'penata_rias_l' => $row['penata_rias_l'],
            'penata_rias_p' => $row['penata_rias_p'],
            'penata_busana_l' => $row['penata_busana_l'],
            'penata_busana_p' => $row['penata_busana_p'],
            'penata_rambut_l' => $row['penata_rambut_l'],
            'penata_rambut_p' => $row['penata_rambut_p'],
            'mekanik_l' => $row['mekanik_l'],
            'mekanik_p' => $row['mekanik_p'],
            'seniman_l' => $row['seniman_l'],
            'seniman_p' => $row['seniman_p'],
            'tabib_l' => $row['tabib_l'],
            'tabib_p' => $row['tabib_p'],
            'paraji_l' => $row['paraji_l'],
            'paraji_p' => $row['paraji_p'],
            'perancang_busana_l' => $row['perancang_busana_l'],
            'perancang_busana_p' => $row['perancang_busana_p'],
            'penterjemah_l' => $row['penterjemah_l'],
            'penterjemah_p' => $row['penterjemah_p'],
            'imam_masjid_l' => $row['imam_masjid_l'],
            'imam_masjid_p' => $row['imam_masjid_p'],
            'pendeta_l' => $row['pendeta_l'],
            'pendeta_p' => $row['pendeta_p'],
            'pastor_l' => $row['pastor_l'],
            'pastor_p' => $row['pastor_p'],
            'wartawan_l' => $row['wartawan_l'],
            'wartawan_p' => $row['wartawan_p'],
            'ustadz_mubaligh_l' => $row['ustadz_mubaligh_l'],
            'ustadz_mubaligh_p' => $row['ustadz_mubaligh_p'],
            'juru_masak_l' => $row['juru_masak_l'],
            'juru_masak_p' => $row['juru_masak_p'],
            'promotor_acara_l' => $row['promotor_acara_l'],
            'promotor_acara_p' => $row['promotor_acara_p'],
            'anggota_dpr_ri_l' => $row['anggota_dpr_ri_l'],
            'anggota_dpr_ri_p' => $row['anggota_dpr_ri_p'],
            'anggota_dpd_ri_l' => $row['anggota_dpd_ri_l'],
            'anggota_dpd_ri_p' => $row['anggota_dpd_ri_p'],
            'anggota_bpk_l' => $row['anggota_bpk_l'],
            'anggota_bpk_p' => $row['anggota_bpk_p'],
            'presiden_l' => $row['presiden_l'],
            'presiden_p' => $row['presiden_p'],
            'wakil_presiden_l' => $row['wakil_presiden_l'],
            'wakil_presiden_p' => $row['wakil_presiden_p'],
            'anggota_mahkamah_konstitusi_l' => $row['anggota_mahkamah_konstitusi_l'],
            'anggota_mahkamah_konstitusi_p' => $row['anggota_mahkamah_konstitusi_p'],
            'anggota_kabinet_kementrian_l' => $row['anggota_kabinet_kementrian_l'],
            'anggota_kabinet_kementrian_p' => $row['anggota_kabinet_kementrian_p'],
            'duta_besar_l' => $row['duta_besar_l'],
            'duta_besar_p' => $row['duta_besar_p'],
            'gubernur_l' => $row['gubernur_l'],
            'gubernur_p' => $row['gubernur_p'],
            'wakil_gubernur_l' => $row['wakil_gubernur_l'],
            'wakil_gubernur_p' => $row['wakil_gubernur_p'],
            'bupati_l' => $row['bupati_l'],
            'bupati_p' => $row['bupati_p'],
            'wakil_bupati_l' => $row['wakil_bupati_l'],
            'wakil_bupati_p' => $row['wakil_bupati_p'],
            'walikota_l' => $row['walikota_l'],
            'walikota_p' => $row['walikota_p'],
            'wakil_walikota_l' => $row['wakil_walikota_l'],
            'wakil_walikota_p' => $row['wakil_walikota_p'],
            'anggota_dprd_prop_l' => $row['anggota_dprd_prop_l'],
            'anggota_dprd_prop_p' => $row['anggota_dprd_prop_p'],
            'anggota_dprd_kab_kota_l' => $row['anggota_dprd_kab_kota_l'],
            'anggota_dprd_kab_kota_p' => $row['anggota_dprd_kab_kota_p'],
            'dosen_l' => $row['dosen_l'],
            'dosen_p' => $row['dosen_p'],
            'guru_l' => $row['guru_l'],
            'guru_p' => $row['guru_p'],
            'pilot_l' => $row['pilot_l'],
            'pilot_p' => $row['pilot_p'],
            'pengacara_l' => $row['pengacara_l'],
            'pengacara_p' => $row['pengacara_p'],
            'notaris_l' => $row['notaris_l'],
            'notaris_p' => $row['notaris_p'],
            'arsitek_l' => $row['arsitek_l'],
            'arsitek_p' => $row['arsitek_p'],
            'akuntan_l' => $row['akuntan_l'],
            'akuntan_p' => $row['akuntan_p'],
            'konsultan_l' => $row['konsultan_l'],
            'konsultan_p' => $row['konsultan_p'],
            'dokter_l' => $row['dokter_l'],
            'dokter_p' => $row['dokter_p'],
            'bidan_l' => $row['bidan_l'],
            'bidan_p' => $row['bidan_p'],
            'perawat_l' => $row['perawat_l'],
            'perawat_p' => $row['perawat_p'],
            'apoteker_l' => $row['apoteker_l'],
            'apoteker_p' => $row['apoteker_p'],
            'psikiater_psikolog_l' => $row['psikiater_psikolog_l'],
            'psikiater_psikolog_p' => $row['psikiater_psikolog_p'],
            'penyiara_televisi_l' => $row['penyiara_televisi_l'],
            'penyiara_televisi_p' => $row['penyiara_televisi_p'],
            'penyiara_radio_l' => $row['penyiara_radio_l'],
            'penyiara_radio_p' => $row['penyiara_radio_p'],
            'pelaut_l' => $row['pelaut_l'],
            'pelaut_p' => $row['pelaut_p'],
            'peneliti_l' => $row['peneliti_l'],
            'peneliti_p' => $row['peneliti_p'],
            'sopir_l' => $row['sopir_l'],
            'sopir_p' => $row['sopir_p'],
            'pialang_l' => $row['pialang_l'],
            'pialang_p' => $row['pialang_p'],
            'paranormal_l' => $row['paranormal_l'],
            'paranormal_p' => $row['paranormal_p'],
            'pedagang_l' => $row['pedagang_l'],
            'pedagang_p' => $row['pedagang_p'],
            'perangkat_desa_l' => $row['perangkat_desa_l'],
            'perangkat_desa_p' => $row['perangkat_desa_p'],
            'kepala_desa_l' => $row['kepala_desa_l'],
            'kepala_desa_p' => $row['kepala_desa_p'],
            'biarawan_biarawati_l' => $row['biarawan_biarawati_l'],
            'biarawan_biarawati_p' => $row['biarawan_biarawati_p'],
            'wiraswasta_l' => $row['wiraswasta_l'],
            'wiraswasta_p' => $row['wiraswasta_p'],
            'anggota_lembaga_tinggi_lainnya_l' => $row['anggota_lembaga_tinggi_lainnya_l'],
            'anggota_lembaga_tinggi_lainnya_p' => $row['anggota_lembaga_tinggi_lainnya_p'],
            'artis_l' => $row['artis_l'],
            'artis_p' => $row['artis_p'],
            'atlit_l' => $row['atlit_l'],
            'atlit_p' => $row['atlit_p'],
            'cheff_l' => $row['cheff_l'],
            'cheff_p' => $row['cheff_p'],
            'manajer_l' => $row['manajer_l'],
            'manajer_p' => $row['manajer_p'],
            'tenaga_tata_usaha_l' => $row['tenaga_tata_usaha_l'],
            'tenaga_tata_usaha_p' => $row['tenaga_tata_usaha_p'],
            'operator_l' => $row['operator_l'],
            'operator_p' => $row['operator_p'],
            'pekerja_pengolahan_keraijin_l' => $row['pekerja_pengolahan_keraijin_l'],
            'pekerja_pengolahan_keraijin_p' => $row['pekerja_pengolahan_keraijin_p'],
            'teknisi_l' => $row['teknisi_l'],
            'teknisi_p' => $row['teknisi_p'],
            'asisten_ahli_l' => $row['asisten_ahli_l'],
            'asisten_ahli_p' => $row['asisten_ahli_p'],
            'pekerjaan_lainnya_l' => $row['pekerjaan_lainnya_l'],
            'pekerjaan_lainnya_p' => $row['pekerjaan_lainnya_p'],
        ]);
    }
}
