<?php

namespace App\Models\Penduduk;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pekerjaan extends Model
{
    use HasFactory,SoftDeletes;
    public $table = 'pekerjaan';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'uuid','kode_wilayah',
        'BELUM/TIDAK BEKERJA_L',
        'BELUM/TIDAK BEKERJA_P',
        'MENGURUS RUMAH TANGGA_L',
        'MENGURUS RUMAH TANGGA_P',
        'PELAJAR/MAHASISWA_L',
        'PELAJAR/MAHASISWA_P',
        'PENSIUNAN_L',
        'PENSIUNAN_P',
        'PEGAWAI NEGERI SIPIL (PNS)_L',
        'PEGAWAI NEGERI SIPIL (PNS)_P',
        'TENTARA NASIONAL INDONESIA (TNI)_L',
        'TENTARA NASIONAL INDONESIA (TNI)_P',
        'KEPOLISIAN RI (POLRI)_L',
        'KEPOLISIAN RI (POLRI)_P',
        'PERDAGANGAN_L',
        'PERDAGANGAN_P',
        'PETANI/PEKEBUN_L',
        'PETANI/PEKEBUN_P',
        'PETERNAK_L',
        'PETERNAK_P',
        'NELAYAN/PERIKANAN_L',
        'NELAYAN/PERIKANAN_P',
        'INDUSTRI_L',
        'INDUSTRI_P',
        'KONSTRUKSI_L',
        'KONSTRUKSI_P',
        'TRANSPORTASI_L',
        'TRANSPORTASI_P',
        'KARYAWAN SWASTA_L',
        'KARYAWAN SWASTA_P',
        'KARYAWAN BUMN_L',
        'KARYAWAN BUMN_P',
        'KARYAWAN BUMD_L',
        'KARYAWAN BUMD_P',
        'KARYAWAN HONORER_L',
        'KARYAWAN HONORER_P',
        'BURUH HARIAN LEPAS_L',
        'BURUH HARIAN LEPAS_P',
        'BURUH TANI/PERKEBUNAN_L',
        'BURUH TANI/PERKEBUNAN_P',
        'BURUH NELAYAN/PERIKANAN_L',
        'BURUH NELAYAN/PERIKANAN_P',
        'BURUH PETERNAKAN_L',
        'BURUH PETERNAKAN_P',
        'PEMBANTU RUMAH TANGGA_L',
        'PEMBANTU RUMAH TANGGA_P',
        'TUKANG CUKUR_L',
        'TUKANG CUKUR_P',
        'TUKANG LISTRIK_L',
        'TUKANG LISTRIK_P',
        'TUKANG BATU_L',
        'TUKANG BATU_P',
        'TUKANG KAYU_L',
        'TUKANG KAYU_P',
        'TUKANG SOL SEPATU_L',
        'TUKANG SOL SEPATU_P',
        'TUKANG LAS/PANDAI BESI_L',
        'TUKANG LAS/PANDAI BESI_P',
        'TUKANG JAHIT_L',
        'TUKANG JAHIT_P',
        'TUKANG GIGI_L',
        'TUKANG GIGI_P',
        'PENATA RIAS_L',
        'PENATA RIAS_P',
        'PENATA BUSANA_L',
        'PENATA BUSANA_P',
        'PENATA RAMBUT_L',
        'PENATA RAMBUT_P',
        'MEKANIK_L',
        'MEKANIK_P',
        'SENIMAN_L',
        'SENIMAN_P',
        'TABIB_L',
        'TABIB_P',
        'PARAJI_L',
        'PARAJI_P',
        'PERANCANG BUSANA_L',
        'PERANCANG BUSANA_P',
        'PENTERJEMAH_L',
        'PENTERJEMAH_P',
        'IMAM MASJID_L',
        'IMAM MASJID_P',
        'PENDETA_L',
        'PENDETA_P',
        'PASTOR_L',
        'PASTOR_P',
        'WARTAWAN_L',
        'WARTAWAN_P',
        'USTADZ/MUBALIGH_L',
        'USTADZ/MUBALIGH_P',
        'JURU MASAK_L',
        'JURU MASAK_P',
        'PROMOTOR ACARA_L',
        'PROMOTOR ACARA_P',
        'ANGGOTA DPR RI_L',
        'ANGGOTA DPR RI_P',
        'ANGGOTA DPD RI_L',
        'ANGGOTA DPD RI_P',
        'ANGGOTA BPK_L',
        'ANGGOTA BPK_P',
        'PRESIDEN_L',
        'PRESIDEN_P',
        'WAKIL PRESIDEN_L',
        'WAKIL PRESIDEN_P',
        'ANGGOTA MAHKAMAH KONSTITUSI_L',
        'ANGGOTA MAHKAMAH KONSTITUSI_P',
        'ANGGOTA KABINET KEMENTRIAN_L',
        'ANGGOTA KABINET KEMENTRIAN_P',
        'DUTA BESAR_L',
        'DUTA BESAR_P',
        'GUBERNUR_L',
        'GUBERNUR_P',
        'WAKIL GUBERNUR_L',
        'WAKIL GUBERNUR_P',
        'BUPATI_L',
        'BUPATI_P',
        'WAKIL BUPATI_L',
        'WAKIL BUPATI_P',
        'WALIKOTA_L',
        'WALIKOTA_P',
        'WAKIL WALIKOTA_L',
        'WAKIL WALIKOTA_P',
        'ANGGOTA DPRD PROP._L',
        'ANGGOTA DPRD PROP._P',
        'ANGGOTA DPRD KAB./KOTA_L',
        'ANGGOTA DPRD KAB./KOTA_P',
        'DOSEN_L',
        'DOSEN_P',
        'GURU_L',
        'GURU_P',
        'PILOT_L',
        'PILOT_P',
        'PENGACARA_L',
        'PENGACARA_P',
        'NOTARIS_L',
        'NOTARIS_P',
        'ARSITEK_L',
        'ARSITEK_P',
        'AKUNTAN_L',
        'AKUNTAN_P',
        'KONSULTAN_L',
        'KONSULTAN_P',
        'DOKTER_L',
        'DOKTER_P',
        'BIDAN_L',
        'BIDAN_P',
        'PERAWAT_L',
        'PERAWAT_P',
        'APOTEKER_L',
        'APOTEKER_P',
        'PSIKIATER/PSIKOLOG_L',
        'PSIKIATER/PSIKOLOG_P',
        'PENYIAR TELEVISI_L',
        'PENYIAR TELEVISI_P',
        'PENYIAR RADIO_L',
        'PENYIAR RADIO_P',
        'PELAUT_L',
        'PELAUT_P',
        'PENELITI_L',
        'PENELITI_P',
        'SOPIR_L',
        'SOPIR_P',
        'PIALANG_L',
        'PIALANG_P',
        'PARANORMAL_L',
        'PARANORMAL_P',
        'PEDAGANG_L',
        'PEDAGANG_P',
        'PERANGKAT DESA_L',
        'PERANGKAT DESA_P',
        'KEPALA DESA_L',
        'KEPALA DESA_P',
        'BIARAWAN/BIARAWATI_L',
        'BIARAWAN/BIARAWATI_P',
        'WIRASWASTA_L',
        'WIRASWASTA_P',
        'ANGGOTA LEMBAGA TINGGI LAINNYA_L',
        'ANGGOTA LEMBAGA TINGGI LAINNYA_P',
        'ARTIS_L',
        'ARTIS_P',
        'ATLIT_L',
        'ATLIT_P',
        'CHEFF_L',
        'CHEFF_P',
        'MANAJER_L',
        'MANAJER_P',
        'TENAGA TATA USAHA_L',
        'TENAGA TATA USAHA_P',
        'OPERATOR_L',
        'OPERATOR_P',
        'PEKERJA PENGOLAHAN KERAJINAN_L',
        'PEKERJA PENGOLAHAN KERAJINAN_P',
        'TEKNISI_L',
        'TEKNISI_P',
        'ASISTEN AHLI_L',
        'ASISTEN AHLI_P',
        'PEKERJAAN LAINNYA_L',
        'PEKERJAAN LAINNYA_P',
        'semester','tahun',
    ];
}
